# generated by datamodel-codegen:
#   filename:  unified_schema.json
#   timestamp: 2025-09-16T19:27:06+00:00

from __future__ import annotations

from datetime import date as date_aliased
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import AnyUrl, BaseModel, Field, confloat, constr


class Publisher(BaseModel):
    name: str = Field(..., description='The name of the publisher.', title='Name')
    url: Optional[AnyUrl] = Field(
        None,
        description='The URL where details of the full dataset, or of the publisher, can be found.',
        title='URL',
    )


class Publisher1(BaseModel):
    name: Optional[str] = Field(
        None, description='The name of the publisher.', title='Name'
    )
    url: AnyUrl = Field(
        ...,
        description='The URL where details of the full dataset, or of the publisher, can be found.',
        title='URL',
    )


class PublicationDetails(BaseModel):
    publicationDate: Union[date_aliased, datetime] = Field(
        ...,
        description='The date on which this statement was published, in full-date (YYYY-MM-DD) or date-time (e.g. YYYY-MM-DDTHH:MM:SSZ) format. See the IETF RFC3339 standard, section 5.6.',
        title='Publication date',
    )
    bodsVersion: constr(regex=r'^(\d+\.)(\d+)$') = Field(
        ...,
        description='The version of the Beneficial Ownership Data Standard to which this Statement conforms, expressed as major.minor (e.g. 0.2 or 1.0). In a published BODS dataset, all Statements MUST have the same major version number.',
        title='BODS Version',
    )
    license: Optional[AnyUrl] = Field(
        None,
        description='A link to the license that applies to this Statement. The canonical URI of the license SHOULD be used. Publishers are encouraged to use a Public Domain Dedication or Open Definition Conformant (http://opendefinition.org/licenses/) license.',
        title='License URL',
    )
    publisher: Union[Publisher, Publisher1] = Field(
        ...,
        description='Details of the organisation or person publishing a Statement.',
        title='Publisher',
    )


class RecordType(Enum):
    entity = 'entity'
    person = 'person'
    relationship = 'relationship'


class RecordStatus(Enum):
    new = 'new'
    updated = 'updated'
    closed = 'closed'


class CreatedBy(BaseModel):
    name: Optional[str] = Field(
        None,
        description='The name of the person, organisation or agent that created this Annotation.',
        title='Name',
    )
    uri: Optional[AnyUrl] = Field(
        None,
        description='An optional URI to identify the person, organisation or agent that created this Annotation.',
        title='URI',
    )


class Motivation(Enum):
    commenting = 'commenting'
    correcting = 'correcting'
    identifying = 'identifying'
    linking = 'linking'
    transformation = 'transformation'


class Annotation(BaseModel):
    statementPointerTarget: Optional[str] = Field(
        None,
        description='An RFC6901 JSON Pointer (https://tools.ietf.org/html/rfc6901) describing the target fragment of the statement that this Annotation applies to, starting from the root of the Statement. An empty string ("") indicates that the Annotation applies to the whole Statement.',
        title='Statement Fragment Pointer',
    )
    creationDate: Optional[Union[date_aliased, datetime]] = Field(
        None,
        description='The date on which this Annotation was created, in full-date (YYYY-MM-DD) or date-time (e.g. YYYY-MM-DDTHH:MM:SSZ) format. See the IETF RFC3339 standard, section 5.6.',
        title='Creation Date',
    )
    createdBy: Optional[CreatedBy] = Field(
        None,
        description='The person, organisation or agent that created this Annotation.',
        title='Created By',
    )
    motivation: Optional[Motivation] = Field(
        None,
        description='The reason for this Annotation, using the annotationMotivation codelist.',
        title='Motivation',
    )
    description: Optional[str] = Field(
        None,
        description='A free text description providing extra information about part of this Statement.',
        title='Description',
    )
    transformedContent: Optional[str] = Field(
        None,
        description="A representation of the Annotation target after the transformation in the `description` field has been applied. This field MUST only be used when the `motivation` is 'transformation'.",
        title='Transformed Content',
    )
    url: Optional[AnyUrl] = Field(
        None,
        description="A linked resource that annotates, provides context for or enhances this Statement. The content of the resource, or the relationship to the statement, MAY be described in the `description` field. This field is REQUIRED if the value of `motivation` is 'linking'.",
        title='URL',
    )


class Type(Enum):
    placeOfBirth = 'placeOfBirth'
    residence = 'residence'
    registered = 'registered'
    service = 'service'
    alternative = 'alternative'
    business = 'business'


class Country(BaseModel):
    name: str = Field(..., description='The name of the country', title='Name')
    code: Optional[constr(min_length=2, max_length=2)] = Field(
        None,
        description='The 2-letter country code (ISO 3166-1) for this country.',
        title='Country Code',
    )


class Jurisdiction(BaseModel):
    name: str = Field(..., description='The name of the jurisdiction', title='Name')
    code: Optional[constr(min_length=2, max_length=6)] = Field(
        None,
        description='The 2-letter country code (ISO 3166-1) or the subdivision code (ISO 3166-2) for the jurisdiction.',
        title='Country or Subdivision Code',
    )


class Identifier1(BaseModel):
    id: Optional[str] = Field(
        None,
        description='The identifier for a person or entity, as issued by the scheme.',
        title='ID',
    )
    scheme: str = Field(
        ...,
        description="For entities, a code from org-id.guide (https://www.org-id.guide) for an identifier-issuing authority (e.g. 'GB-COH'). For natural persons, a value with the pattern {JURISDICTION}-{TYPE} where JURISDICTION is an ISO 3166-1 3-digit country code and TYPE is one of PASSPORT, TAXID or IDCARD.",
        title='Scheme Code',
    )
    schemeName: Optional[str] = Field(
        None,
        description='The name of the identifier-issuing authority.',
        title='Scheme Name',
    )
    uri: Optional[AnyUrl] = Field(
        None,
        description='A canonical URI (https://en.wikipedia.org/wiki/Uniform_Resource_Identifier) for the identifier and associated details of the person or entity, if one exists.',
        title='URI',
    )


class Identifier2(BaseModel):
    id: Optional[str] = Field(
        None,
        description='The identifier for a person or entity, as issued by the scheme.',
        title='ID',
    )
    scheme: Optional[str] = Field(
        None,
        description="For entities, a code from org-id.guide (https://www.org-id.guide) for an identifier-issuing authority (e.g. 'GB-COH'). For natural persons, a value with the pattern {JURISDICTION}-{TYPE} where JURISDICTION is an ISO 3166-1 3-digit country code and TYPE is one of PASSPORT, TAXID or IDCARD.",
        title='Scheme Code',
    )
    schemeName: str = Field(
        ...,
        description='The name of the identifier-issuing authority.',
        title='Scheme Name',
    )
    uri: Optional[AnyUrl] = Field(
        None,
        description='A canonical URI (https://en.wikipedia.org/wiki/Uniform_Resource_Identifier) for the identifier and associated details of the person or entity, if one exists.',
        title='URI',
    )


class Identifier3(BaseModel):
    id: Optional[str] = Field(
        None,
        description='The identifier for a person or entity, as issued by the scheme.',
        title='ID',
    )
    scheme: str = Field(
        ...,
        description="For entities, a code from org-id.guide (https://www.org-id.guide) for an identifier-issuing authority (e.g. 'GB-COH'). For natural persons, a value with the pattern {JURISDICTION}-{TYPE} where JURISDICTION is an ISO 3166-1 3-digit country code and TYPE is one of PASSPORT, TAXID or IDCARD.",
        title='Scheme Code',
    )
    schemeName: str = Field(
        ...,
        description='The name of the identifier-issuing authority.',
        title='Scheme Name',
    )
    uri: Optional[AnyUrl] = Field(
        None,
        description='A canonical URI (https://en.wikipedia.org/wiki/Uniform_Resource_Identifier) for the identifier and associated details of the person or entity, if one exists.',
        title='URI',
    )


class Identifier(BaseModel):
    __root__: Union[Identifier1, Identifier2, Identifier3] = Field(
        ...,
        description='An identifier that has been assigned to a person or entity. `scheme` or `schemeName` (or both) MUST be included in an Identifier object.',
        title='Identifier',
    )


class Reason(Enum):
    noBeneficialOwners = 'noBeneficialOwners'
    subjectUnableToConfirmOrIdentifyBeneficialOwner = (
        'subjectUnableToConfirmOrIdentifyBeneficialOwner'
    )
    interestedPartyHasNotProvidedInformation = (
        'interestedPartyHasNotProvidedInformation'
    )
    subjectExemptFromDisclosure = 'subjectExemptFromDisclosure'
    interestedPartyExemptFromDisclosure = 'interestedPartyExemptFromDisclosure'
    unknown = 'unknown'
    informationUnknownToPublisher = 'informationUnknownToPublisher'


class UnspecifiedRecord(BaseModel):
    reason: Reason = Field(
        ...,
        description='The reason that a person or entity cannot be specified, using the unspecifiedReason codelist.',
        title='Reason',
    )
    description: Optional[str] = Field(
        None,
        description='Additional information about the absence of details for a person or entity. This field may be used to provide set phrases from a source system, or a free text explanation.',
        title='Description',
    )


class TypeEnum(Enum):
    selfDeclaration = 'selfDeclaration'
    officialRegister = 'officialRegister'
    thirdParty = 'thirdParty'
    primaryResearch = 'primaryResearch'
    verified = 'verified'


class AssertedByItem(BaseModel):
    name: Optional[str] = Field(
        None, description='The name of the agent making the assertion', title='Name'
    )
    uri: Optional[AnyUrl] = Field(
        None,
        description='An optional URI to identify the agent making the assertion',
        title='URI',
    )


class Source(BaseModel):
    type: Optional[List[TypeEnum]] = Field(
        None,
        description="The types of the source, using the sourceType codelist. Include 'verified' in the array if the information in the Statement has undergone a verification process.",
        title='Source Type',
    )
    description: Optional[str] = Field(
        None,
        description='Additional, free text information about the source of information.',
        title='Description',
    )
    url: Optional[AnyUrl] = Field(
        None,
        description='The external URL from which this information was fetched, if relevant. Or, if relevant, a URL providing additional detail on how this information was sourced.',
        title='Source URL',
    )
    retrievedAt: Optional[Union[date_aliased, datetime]] = Field(
        None,
        description='A timestamp indicating when this information was imported from an external system, in full-date (YYYY-MM-DD) or date-time (e.g. YYYY-MM-DDTHH:MM:SSZ) format. See the IETF RFC3339 standard, section 5.6.',
        title='Retrieved At',
    )
    assertedBy: Optional[List[AssertedByItem]] = Field(
        None,
        description='The people or organisations providing the information asserted in this Statement. This may include the declaring subject of a self-declaration, or the name of an agent making a declaration on their behalf. If this Statement has been verified, the array may include the name of the organisation providing verification.',
        title='Asserted By',
    )


class IdScheme(Enum):
    isin = 'isin'
    figi = 'figi'
    cusip = 'cusip'
    cins = 'cins'


class Security(BaseModel):
    idScheme: Optional[IdScheme] = Field(
        None,
        description='The scheme under which the security has been issued a unique, persistent identifier, using the securitiesIdentifierSchemes codelist.',
        title='Identifier Scheme',
    )
    id: Optional[str] = Field(
        None,
        description='The unique identifier of the security as issued under the `idScheme`.',
        title='Identifier',
    )
    ticker: str = Field(
        ...,
        description='The stock ticker identifying this security on the named stock exchange.',
        title='Stock Ticker',
    )


class SecuritiesListing(BaseModel):
    marketIdentifierCode: Optional[str] = Field(
        None,
        description='The Market Identifier Code (MIC) of the market on which the security is traded. Where the security is traded on a segment of an exchange, this is the MIC of the segment. Where it is traded on the main exchange, this is the MIC of the main exchange and MUST match the `operatingMarketIdentifierCode`. MICs are allocated and managed under ISO standard 10383.',
        title='Market Identifier Code (MIC)',
    )
    operatingMarketIdentifierCode: Optional[str] = Field(
        None,
        description='The Market Identifier Code (MIC) of the main exchange or trading platform handling trades in this security. Where the security is traded on a segment of an exchange, this is the MIC of the parent exchange or trading platform. Where it is traded on the main exchange, this is the MIC of that main exchange and MUST match the `marketIdentifierCode`. MICs are allocated and managed under ISO standard 10383.',
        title='Operating Market Identifier Code (Operating MIC)',
    )
    stockExchangeJurisdiction: constr(min_length=2, max_length=6) = Field(
        ...,
        description='The 2-letter country code (ISO 3166-1) or the subdivision code (ISO 3166-2) for the jurisdiction under which the exchange, market or trading platform is regulated.',
        title='Stock Exchange Jurisdiction',
    )
    stockExchangeName: str = Field(
        ...,
        description="The name of the exchange, market or trading platform on which the security is traded. If the security is traded on a segment of the exchange, then the name SHOULD include both elements. For example, 'London Stock Exchange - MTF'.",
        title='Stock Exchange Name',
    )
    security: Security = Field(
        ...,
        description='Identifying information of the stock or other security.',
        title='Security',
    )


class Type1(Enum):
    registeredEntity = 'registeredEntity'
    legalEntity = 'legalEntity'
    arrangement = 'arrangement'
    anonymousEntity = 'anonymousEntity'
    unknownEntity = 'unknownEntity'
    state = 'state'
    stateBody = 'stateBody'


class Subtype(Enum):
    governmentDepartment = 'governmentDepartment'
    stateAgency = 'stateAgency'
    other = 'other'
    trust = 'trust'
    nomination = 'nomination'


class EntityType(BaseModel):
    type: Type1 = Field(
        ...,
        description='The general form of the entity, using the entityType codelist.',
        title='Type',
    )
    subtype: Optional[Subtype] = Field(
        None,
        description='The particular form of the entity, where relevant, using the entitySubtype codelist. The value MUST align with the `entityType` value.',
        title='Subtype',
    )
    details: Optional[str] = Field(
        None,
        description="This may be used to provide a local name for this type of entity, or any further information to identify the type of entity. For example, in Finland 'ministeriö' for a government department.",
        title='Details',
    )


class FormedByStatute(BaseModel):
    name: Optional[str] = Field(
        None, description='The name of the law. ', title='Statute Name'
    )
    date: Optional[date_aliased] = Field(
        None,
        description='The date on which the law came into force. The date MUST be given in YYYY-MM-DD format. Where a precise month or date are not available, the value may be rounded to the first day of the (first) month. This rounding SHOULD be noted in accompanying guidance (such as a publication policy or data use guide).',
        title='Date',
    )


class Type2(Enum):
    shareholding = 'shareholding'
    votingRights = 'votingRights'
    appointmentOfBoard = 'appointmentOfBoard'
    otherInfluenceOrControl = 'otherInfluenceOrControl'
    seniorManagingOfficial = 'seniorManagingOfficial'
    settlor = 'settlor'
    trustee = 'trustee'
    protector = 'protector'
    beneficiaryOfLegalArrangement = 'beneficiaryOfLegalArrangement'
    rightsToSurplusAssetsOnDissolution = 'rightsToSurplusAssetsOnDissolution'
    rightsToProfitOrIncome = 'rightsToProfitOrIncome'
    rightsGrantedByContract = 'rightsGrantedByContract'
    conditionalRightsGrantedByContract = 'conditionalRightsGrantedByContract'
    controlViaCompanyRulesOrArticles = 'controlViaCompanyRulesOrArticles'
    controlByLegalFramework = 'controlByLegalFramework'
    boardMember = 'boardMember'
    boardChair = 'boardChair'
    unknownInterest = 'unknownInterest'
    unpublishedInterest = 'unpublishedInterest'
    enjoymentAndUseOfAssets = 'enjoymentAndUseOfAssets'
    rightToProfitOrIncomeFromAssets = 'rightToProfitOrIncomeFromAssets'
    nominee = 'nominee'
    nominator = 'nominator'


class DirectOrIndirect(Enum):
    direct = 'direct'
    indirect = 'indirect'
    unknown = 'unknown'


class Share(BaseModel):
    exact: Optional[confloat(ge=0.0, le=100.0)] = Field(
        None,
        description='The exact share of this interest held (if available).',
        title='Exact percentage',
    )
    maximum: Optional[confloat(ge=0.0, le=100.0)] = Field(
        None,
        description='The inclusive upper bound of the share of this interest.',
        title='Maximum Percentage',
    )
    minimum: Optional[confloat(ge=0.0, le=100.0)] = Field(
        None,
        description='The inclusive lower bound of the share of this interest.',
        title='Minimum Percentage',
    )
    exclusiveMinimum: Optional[confloat(ge=0.0, le=100.0)] = Field(
        None,
        description='The exclusive lower bound of the share of this interest.',
        title='Exclusive Minimum percentage',
    )
    exclusiveMaximum: Optional[confloat(ge=0.0, le=100.0)] = Field(
        None,
        description='The exclusive upper bound of the share of this interest.',
        title='Exclusive Maximum Percentage',
    )


class Interest(BaseModel):
    type: Optional[Type2] = Field(
        None,
        description='The nature of the interest, using the interestType codelist.',
        title='Type of Interest',
    )
    directOrIndirect: Optional[DirectOrIndirect] = Field(
        None,
        description="How directly the interest is exercised by the interested party. The value MUST be 'indirect' if intermediate entities or agents are known to exist, and MUST be 'direct' if such intermediaries are known not to exist. Otherwise the value MUST be 'unknown'.",
        title='Direct or Indirect',
    )
    beneficialOwnershipOrControl: Optional[bool] = Field(
        None,
        description="Whether this interest (alone or with others) means the interested party is a beneficial owner of the subject. If 'true' the interested party MUST be a natural person. The definition of 'beneficial owner' in operation SHOULD be noted in accompanying guidance (such as a publication policy or data use guide).",
        title='Beneficial Ownership or Control',
    )
    details: Optional[str] = Field(
        None,
        description='The local name given to this kind of interest, or further information (semi-structured or unstructured) to clarify the nature of the interest.',
        title='Details',
    )
    share: Optional[Share] = Field(
        None,
        description='The proportion of this type of interest held by the interested party, where an interest is countable. Provide the `exact` percentage if known. Otherwise, `minimum` (or `exclusiveMinimum`) and `maximum` (or `exclusiveMaximum`) can be used to record the range into which the proportion falls. (The `minimum` and `maximum` values are inclusive.)',
        title='Percentage Share',
    )
    startDate: Optional[date_aliased] = Field(
        None,
        description='The date from which this interest was active. The date MUST be given in YYYY-MM-DD format. Where a precise month or date are unknown, the value may be rounded to the first day of the (first) month. This rounding SHOULD be noted in accompanying guidance (such as a publication policy or data use guide).',
        title='Start Date',
    )
    endDate: Optional[date_aliased] = Field(
        None,
        description='The date from which this interest ceased to exist. The date MUST be given in YYYY-MM-DD format. Where a precise month or date are unknown, the value may be rounded to the first day of the (first) month. This rounding SHOULD be noted in accompanying guidance (such as a publication policy or data use guide).',
        title='End Date',
    )


class RelationshipRecordDetails(BaseModel):
    isComponent: bool = Field(
        ...,
        description="Whether this relationship is a component of a wider indirect relationship. Where `isComponent` is 'true': (1) the `recordId` of this secondary Relationship Statement MUST be an element in the `componentRecords` array of that primary Relationship Statement, (2) this Relationship Statement MUST come before that primary Relationship Statement in a BODS package or stream, (3) the replacement of this Relationship Statement SHOULD be considered when replacing the primary Relationship Statement, and (4) the primary Relationship Statement MUST have an `isComponent` value of 'false'. Where `isComponent` is 'false', this Relationship Statement is the primary declaration of the relationship between the `subject` and the `interestedParty`.",
        title='Is component',
    )
    componentRecords: Optional[List[str]] = Field(
        None,
        description="The `recordId` values of all component records that provide detail about this relationship between the `subject` and the `interestedParty` (if it is indirect). If this relationship has components, its own `isComponent` value MUST be 'false'.",
        title='Component Record IDs',
    )
    subject: Union[str, UnspecifiedRecord] = Field(
        ...,
        description='The `recordId` for the subject of the relationship, or a reason why the subject cannot be specified. The subject MUST be an entity.',
        title='Subject',
    )
    interestedParty: Union[str, UnspecifiedRecord] = Field(
        ...,
        description='The `recordId` for the interested party in the relationship, or an Unspecified Record object with a reason for why this information has not been disclosed. The interested party MAY be an entity or a person. An Unspecified Record SHOULD only be used where no information at all is known about interested parties beyond this point of the beneficial ownership network. If the interested party is known to be an entity or person but their particular identity is unavailable, a `recordId` for them SHOULD be provided here (and the their `recordDetails.[person|entity]Type` should indicate that they are anonymous or unknown).',
        title='Interested Party',
    )
    interests: Optional[List[Interest]] = Field(
        None,
        description='A description of the interests held by the interested party in the subject.',
        title='Interests',
    )


class Statement(BaseModel):
    statementId: constr(min_length=32, max_length=64) = Field(
        ...,
        description='A persistent globally unique identifier for this Statement. Length MUST be 32 - 64 characters (inclusive).',
        title='Statement Identifier',
    )
    statementDate: Union[date_aliased, datetime] = Field(
        ...,
        description='The date on which this statement was declared by the source, in full-date (YYYY-MM-DD) or date-time (e.g. YYYY-MM-DDTHH:MM:SSZ) format. See the IETF RFC3339 standard, section 5.6.',
        title='Statement Date',
    )
    annotations: Optional[List[Annotation]] = Field(
        None,
        description='Annotations about this Statement or parts of this Statement',
        title='Annotations',
    )
    publicationDetails: Optional[PublicationDetails] = Field(
        None,
        description='Information concerning the publication of this Statement.',
        title='Publication Details',
    )
    source: Optional[Source] = Field(
        None,
        description='The source of information in this statement. Each statement SHOULD contain source information.',
        title='Source',
    )
    declaration: Optional[str] = Field(
        None,
        description='An identifier or reference for a declaration within the publisher’s system. Where a Statement is a claim from a particular declaration (made at a point in time by a `source` about a `declarationSubject`) this field identifies the declaration.',
        title='Declaration Reference',
    )
    declarationSubject: str = Field(
        ...,
        description='A `recordId` value for the subject of a beneficial ownership network (always an entity or person).',
        title='Declaration Subject',
    )
    recordId: str = Field(
        ...,
        description="A unique identifier for the record (within the publisher's system) to which this Statement relates. (A record captures information about an entity, natural person or relationship within the beneficial ownership network of a particular declaration subject.)",
        title='Record Identifier',
    )
    recordType: RecordType = Field(
        ...,
        description="The type of record (within the publisher's system) to which this Statement relates: entity, person, or relationship.",
        title='Record Type',
    )
    recordStatus: Optional[RecordStatus] = Field(
        None,
        description="The lifecycle status of the record (within the publisher's system) to which this Statement relates, using the recordStatus codelist.",
        title='Record Status',
    )
    recordDetails: Dict[str, Any] = Field(
        ...,
        description='The details of the entity, person or relationship as declared on the Statement Date.',
        title='Record Details',
    )


class Address(BaseModel):
    type: Optional[Type] = Field(
        None,
        description='The function of the address, using the addressType codelist.',
        title='Type',
    )
    address: Optional[str] = Field(
        None,
        description='The address, with each line or component separated by a line-break or comma.',
        title='Address',
    )
    postCode: Optional[str] = Field(
        None, description='The postal code for this address.', title='Postcode'
    )
    country: Optional[Country] = Field(
        None, description='The country for this address.', title='Country'
    )


class PublicListing(BaseModel):
    hasPublicListing: bool = Field(
        ...,
        description='Whether the entity is a publicly listed company.',
        title='Has Public Listing',
    )
    companyFilingsURLs: Optional[List[AnyUrl]] = Field(
        None,
        description='URL or URLs where regulatory filings related to major holdings can be retrieved. URLs may point to pages maintained by regulatory bodies, stock exchanges or by the company itself.',
        title='Company Filings URLs',
    )
    securitiesListings: Optional[List[SecuritiesListing]] = Field(
        None,
        description="Details of the entity's securities and the public exchanges and markets on which they are traded. All equity securities SHOULD be listed here, plus any other securities from which beneficial ownership might be derived. Where a security is traded on more than one market, there SHOULD be an entry for each market (or market segment).",
        title='Securities Listings',
    )


class EntityRecordDetails(BaseModel):
    isComponent: bool = Field(
        ...,
        description="Whether this entity is a component in an indirect relationship. Where `isComponent` is 'true': (1) the `recordId` of this entity MUST be an element in the `componentRecords` array of that primary Relationship Statement, (2) this Entity Statement MUST come before that primary Relationship Statement in a BODS package or stream, (3) the replacement of this Entity Statement SHOULD be considered when replacing the primary Relationship Statement. The primary Relationship statement MUST have a `isComponent` value of 'false'.",
        title='Is component',
    )
    entityType: EntityType = Field(
        ...,
        description='The form of the entity described in the Statement.',
        title='Entity Type',
    )
    unspecifiedEntityDetails: Optional[UnspecifiedRecord] = Field(
        None, description='An explanation of why an entity is anonymous or unknown.'
    )
    name: Optional[str] = Field(
        None, description='The declared name of this entity.', title='Entity Name'
    )
    alternateNames: Optional[List[str]] = Field(
        None,
        description='An array of other names this entity is known by.',
        title='Alternative Names',
    )
    jurisdiction: Optional[Jurisdiction] = Field(
        None,
        description="The jurisdiction in which this entity was registered or created (for legal and registered entities, and arrangements). Or the state's jurisdiction (for states and state bodies).",
        title='Jurisdiction',
    )
    identifiers: Optional[List[Identifier]] = Field(
        None,
        description='One or more official identifiers for this entity. Where available, official registration numbers should be provided.',
        title='Identifiers',
    )
    foundingDate: Optional[date_aliased] = Field(
        None,
        description='The date on which this entity was founded, created or registered. The date MUST be given in YYYY-MM-DD format. Where a precise month or date are not available, the value may be rounded to the first day of the (first) month. This rounding SHOULD be noted in accompanying guidance (such as a publication policy or data use guide).',
        title='Founding Date',
    )
    dissolutionDate: Optional[date_aliased] = Field(
        None,
        description='The date on which this entity was dissolved or ceased, if it is no longer active. The date MUST be given in YYYY-MM-DD format. Where a precise month or date are not available, the value may be rounded to the first day of the (first) month. This rounding SHOULD be noted in accompanying guidance (such as a publication policy or data use guide).',
        title='Dissolution Date',
    )
    addresses: Optional[List[Address]] = Field(
        None, description='One or more addresses for this entity.', title='Addresses'
    )
    uri: Optional[AnyUrl] = Field(
        None,
        description='Where a persistent URI (https://en.wikipedia.org/wiki/Uniform_Resource_Identifier) is available for this entity this should be included.',
        title='URI',
    )
    publicListing: Optional[PublicListing] = Field(
        None,
        description='Details of a publicly listed company, its securities (shares and other tradable financial instruments related to the entity), and related regulatory filings.',
        title='Public Listing',
    )
    formedByStatute: Optional[FormedByStatute] = Field(
        None,
        description='The law which mandated the formation of the entity described in the statement, where applicable. This information SHOULD be provided where a state has created an agency or other entity with specific legislation.',
        title='Formed by Statute',
    )


class Statements(BaseModel):
    __root__: List[Statement] = Field(
        ..., description='An array of Statements.', title='Statements'
    )
