# Red flags and coherence

## Overall purpose and objective
The overall purpose and objective of the cleaning and verification process is to prepare the data for conversion into a SQLite database (Datasette). As such, the data should follow database best practices.

## Specific purpose of this notebook
This notebook is for checking duplicates in the data and coherence. Particularly, we want to check for:
- Possible red flag rows for each table.
- The companies/agencies in the company and agency lists correspond to companies/agencies in the company data
- The revenue reported are consistent between the Government revenues and Company data tables

## Assumptions
- Some combinations of fields should be unique
- The values should be cohrent across tables

## Why this matters 
- Inserting the data in a proper database and assigning EITI IDs require a high confidence in the data quality to avoid downstream issues. Duplicates and non-coherence of the data decreases this level of confidence.

## Findings
- There are a significant number (>40%) of possible red flag columns (duplications) in all of the tables except for Part 1 - About
- Most are due to missing values in the columns that are used to check for uniqueness/duplication
- Most should easily be reconciled by differentiating them using the Country and Year columns
- There are several rows (i.e. companies, agencies, projects) in the Part 3 tables that are not in Part 5 - Company data and vice versa.
- 70% of the reports do not have the same computed revenue values based on Part 4 - Government revenues and Part 5 - Company data

More specific findings below.

## Analysis

### Red flags in the tables due to possible duplication

In this part, we look for red flags in the tables by looking at how similar rows are based on a combination of columns that, when taken together, should form a unique identifier for the row.

In [2]:
# import libraries and data

import pandas as pd
import numpy as np
from os import path
from functools import reduce
from pprint import pprint
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
from itertools import combinations

file_dir = "data/consolidated/"
file_dir_old = "data/consolidated/backup/old"

# load the csvs into data frames
df_part_1 = pd.read_csv(path.join(file_dir, "Part 1 - About.csv"))
df_part_3a = pd.read_csv(path.join(file_dir, "Part 3 - Reporting companies' list.csv"))
df_part_3b = pd.read_csv(path.join(file_dir, "Part 3 - Reporting government entities list.csv"))
df_part_3c = pd.read_csv(path.join(file_dir, "Part 3 - Reporting projects' list.csv"))
df_part_4 = pd.read_csv(path.join(file_dir, "Part 4 - Government revenues.csv"))
df_part_5 = pd.read_csv(path.join(file_dir, "Part 5 - Company data.csv"))
# df_part_5 = pd.read_csv(path.join(file_dir, "Part 5 - Company data.csv"), low_memory=False)

df_list = [df_part_1, df_part_3a, df_part_3b, df_part_3c, df_part_4, df_part_5]
df_dict = {"Part 1 - About.csv": df_part_1,
           "Part 3 - Reporting companies' list.csv": df_part_3a,
           "Part 3 - Reporting government entities list.csv": df_part_3b,
           "Part 3 - Reporting projects' list.csv": df_part_3c,
           "Part 4 - Government revenues.csv": df_part_4,
           "Part 5 - Company data.csv": df_part_5
          }

# OPTIONAL COLUMNS
part_3a_opt = ["Stock exchange listing or company website", 
               "Audited financial statement (or balance sheet, cash flows, profit/loss statement if unavailable)"]
part_3b_opt = ["ID number (if applicable)"]
part_5_opt = ["In-kind volume (if applicable)", "Unit (if applicable)", "Comments"]

# only include fields that are non-optional
df_part_1_non_opt = df_part_1.copy()
df_part_3a_non_opt = df_part_3a.copy().drop(columns=part_3a_opt)               
df_part_3b_non_opt = df_part_3b.copy().drop(columns=part_3b_opt)
df_part_3c_non_opt = df_part_3c.copy()
df_part_4_non_opt = df_part_4.copy()
df_part_5_non_opt = df_part_5.copy().drop(columns=part_5_opt)

df_list_non_opt = [df_part_1_non_opt, df_part_3a_non_opt, df_part_3b_non_opt, df_part_3c_non_opt, df_part_4_non_opt, df_part_5_non_opt]
df_dict_non_opt = {"Part 1 - About.csv": df_part_1_non_opt,
           "Part 3 - Reporting companies' list.csv": df_part_3a_non_opt,
           "Part 3 - Reporting government entities list.csv": df_part_3b_non_opt,
           "Part 3 - Reporting projects' list.csv": df_part_3c_non_opt,
           "Part 4 - Government revenues.csv": df_part_4_non_opt,
           "Part 5 - Company data.csv": df_part_5_non_opt
          }

In [2]:
def get_column_combinations(columns, min_cols_diff):
    '''
    Get unique column combinations that will be used for determining problematic rows (i.e. possible duplicates).

    Parameters:
    - columns (list or iterable): A list of column names or identifiers to be used for forming combinations.
    - min_cols_diff (int): The minimum number of columns to form unique combinations.

    Returns:
    list: A list of tuples representing unique combinations of columns.

    Example:
    >>> columns = ['col1', 'col2', 'col3']
    >>> min_cols_diff = 2
    >>> get_column_combinations(columns, min_cols_diff)
    [('col1', 'col2'), ('col1', 'col3'), ('col2', 'col3')]
    '''

    all_combinations = []
    for x in range(min_cols_diff, len(columns) + 1):
        all_combinations.extend(combinations(columns, x))

    return all_combinations

# TEST: Uncomment lines below and run
# OUTPUT: 4 unique column combinations
# columns = ["Full name of agency", "Agency type", "Total reported"]
# column_combinations = get_column_combinations(columns, 2)
# print(f'There are {len(column_combinations)} combinations:')
# pprint(column_combinations)

In [3]:
def add_rowid(df):
    '''
    Add a row identifier (rowid) column to the DataFrame.

    Parameters:
    - df (pandas.DataFrame): The input DataFrame.

    Returns:
    pandas.DataFrame: A new DataFrame with an additional 'rowid' column.

    Example:
    >>> data = {'col1': [1, 2, 3], 'col2': ['a', 'b', 'c']}
    >>> df = pd.DataFrame(data)
    >>> add_rowid(df)
       col1 col2  rowid
    0     1    a      0
    1     2    b      1
    2     3    c      2
    '''

    df_rowid = df.copy()
    df_rowid["rowid"] = range(len(df_rowid))

    return df_rowid    

In [4]:
def get_redflags(df, columns, min_cols_diff):
    '''
    Get unique column combinations and find problematic rows (duplicates) based on specified columns.

    Parameters:
    - df (pandas.DataFrame): The input DataFrame.
    - columns (list or iterable): A list of column names or identifiers to be used for forming combinations.
    - min_cols_diff (int): The minimum number of columns to form unique combinations (i.e. minimum numbers of columns of difference to be considered unique).

    Returns:
    pandas.DataFrame: DataFrame containing unique rows among problematic rows.

    Example:
    >>> data = {'col1': [1, 2, 2, 3, 4], 'col2': ['a', 'b', 'b', 'c', 'd']}
    >>> df = pd.DataFrame(data)
    >>> columns_for_combinations = ['col1', 'col2']
    >>> min_cols_diff = 2
    >>> get_redflags(df, columns_for_combinations, min_cols_diff)
       col1 col2
    0     2    b
    '''

    # Step 1: Create a copy of the DataFrame and add rowid
    df_copy = df.copy()
    df_copy['rowid'] = range(len(df_copy))

    # Step 2: Get column combinations
    all_combinations = []
    for x in range(min_cols_diff, len(columns) + 1):
        all_combinations.extend(combinations(columns, x))

    # Step 3: Find problematic rows for each column combination
    problematic_rows = pd.DataFrame()
    for combination in all_combinations:
        duplicated_rows = df_copy[df_copy.duplicated(subset=list(combination), keep=False)]
        problematic_rows = pd.concat([problematic_rows, duplicated_rows], ignore_index=False)

    # Step 4: Get unique rows among problematic rows
    unique_problematic_rows = problematic_rows.drop_duplicates()

    return unique_problematic_rows

In [5]:
def get_redflags2(df, min_cols_diff):
    '''
    Get unique column combinations and find problematic rows (duplicates) based on specified columns.

    Parameters:
    - df (pandas.DataFrame): The input DataFrame.
    - min_cols_diff (int): The minimum number of columns to form unique combinations (i.e. minimum numbers of columns of difference to be considered unique).

    Returns:
    pandas.DataFrame: DataFrame containing unique rows among problematic rows.
    '''
    
    problematic_rows = pd.DataFrame()

    for index, row in df.iterrows():
        current_row = row
        other_rows = df.drop(index)  # Drop the current row

        frows = (other_rows.values == current_row.values)

        rows_with_num_false = other_rows[(~frows).sum(axis=1) <= min_cols_diff]
        problematic_rows = pd.concat([problematic_rows, rows_with_num_false], ignore_index=False)

    unique_problematic_rows = problematic_rows.drop_duplicates()

    return unique_problematic_rows


In [6]:
def table_groupby(df, column, ascending=True):

    return df.groupby(column).size().reset_index(name='Number of Rows').sort_values(by="Number of Rows", ascending=ascending)

In [7]:
def num_rf_rows(df1, df2):
    
    perc = 100 * df2.shape[0] / df1.shape[0]
    print(f'{df2.shape[0]} out of {df1.shape[0]} ({perc:.2f}%) rows are possible red flags')

In [8]:
def num_compare_rows(df1, df2):
    
    perc = 100 * df2.shape[0] / df1.shape[0]
    print(f'{df2.shape[0]} out of {df1.shape[0]} ({perc:.2f}%) rows')

#### Part 1 - About

#### Results
- 0 redflag columns

In [10]:
redflags_part_1_2 = get_redflags2(df_part_1, 2)
num_rf_rows(df_part_1, redflags_part_1_2)
display(redflags_part_1_2)

0 out of 73 (0%) rows are possible red flags


Empty DataFrame
Columns: [Country or area name, ISO Alpha-3 Code, National currency name, National currency ISO-4217, Start Date, End Date, Has an EITI Report been prepared by an Independent Administrator?, What is the name of the company?, Date that the EITI Report was made public, URL, EITI Report, Does the government systematically disclose EITI data at a single location?, Publication date of the EITI data, Website link (URL) to EITI data, Are there other files of relevance?, Date that other file was made public, URL, Does the government have an open data policy?, Open data portal / files, Oil, Gas, Mining (incl. Quarrying), Other, non-upstream sectors, If yes, please specify name (insert new rows if multiple), Number of reporting government entities (incl SOEs if recipient), Number of reporting companies (incl SOEs if payer), Reporting currency (ISO-4217 currency codes), Exchange rate used: 1 USD = , Exchange rate source (URL,…), … by revenue stream, … by government agency, … by company, … by project, Systematically disclosed, Through EITI Reporting, Not applicable, Not available, Name, Organisation, Email address]
Index: []

[0 rows x 39 columns]

#### Part 3 - Reporting companies' list

#### Results
- 73 out of 3792 (2%) rows are possible red flags

In [45]:
redflags_part_3a_2 = get_redflags2(df_part_3a, 2)
num_rf_rows(df_part_3a, redflags_part_3a_2)
display(redflags_part_3a_2)

73 out of 3792 (1.93%) rows are possible red flags


Full company name Company type  \
107   بلال موسی زی دمعدنی ډبرو استخراج او پروسس شرکت...      Private   
115   حبیب شهاب تا لک اومر مرواستخراج او پروسس شر کت...      Private   
216   نبی افغان دمعدن استخراج او پروسس شر کت Nabi Af...      Private   
119   ستندر شو کا ڼی دپرو سس او استخراج شر کت Standa...      Private   
18                        Bilal Musazai Company Limited      Private   
...                                                 ...          ...   
3772                                     TEKTON MINERAL      Private   
3770       Société de Concassage de Hadjer Lamis (SCHL)      Private   
3777                                Manejem Company Ltd      Private   
3781                    Chad construction Materials S.A      Private   
3776                                               ETEP      Private   

     Company ID number  Sector Commodities (comma-seperated)  \
107         1009592088   Other                          Talc   
115         1013655012   Other                          Talc   
216         1010360087   Other                          Talc   
119         1016525014   Other                          Talc   
18          1009592088   Other                          Talc   
...                ...     ...                           ...   
3772     Not available  Mining                          Gold   
3770     Not available  Mining                    Granulates   
3777     Not available  Mining                           BTP   
3781     Not available  Mining                           BTP   
3776     Not available  Mining                           BTP   

     Stock exchange listing or company website  \
107                            Not applicable    
115                            Not applicable    
216                            Not applicable    
119                            Not applicable    
18                             Not applicable    
...                                        ...   
3772                             Not available   
3770                             Not available   
3777                             Not available   
3781                             Not available   
3776                             Not available   

     Audited financial statement (or balance sheet, cash flows, profit/loss statement if unavailable)  \
107                                      Not available                                                  
115                                      Not available                                                  
216                                      Not available                                                  
119                                      Not available                                                  
18                                       Not available                                                  
...                                                 ...                                                 
3772                                      Not available                                                 
3770                                      Not available                                                 
3777                                      Not available                                                 
3781                                      Not available                                                 
3776                                      Not available                                                 

     Payments to Governments Report      Country ISO Code  Year  Start Date  \
107                          367503  Afghanistan      AFG  2018  2017-12-21   
115                           25459  Afghanistan      AFG  2018  2017-12-21   
216                             170  Afghanistan      AFG  2018  2017-12-21   
119                           21539  Afghanistan      AFG  2018  2017-12-21   
18                         12467181  Afghanistan      AFG  2018  2017-12-21   
...                             ...          ...      ...   ...     

#### Part 3 - Reporting govenment agencies' list

#### Results
135 out of 547 (24.68%) rows are possible red flags

In [15]:
redflags_part_3b_2 = get_redflags2(df_part_3b, 2)
num_rf_rows(df_part_3b, redflags_part_3b_2)
display(redflags_part_3b_2)

140 out of 547 (25.59%) rows are possible red flags


Full name of agency  \
1             Ministry of Finance (Customs Department)   
2    Ministry of Mines and Petroleum (Revenue Depar...   
3             National Environmental Protection Agency   
4                    Ministry of Industry and Commerce   
0             Ministry of Finance (Revenue Department)   
..                                                 ...   
543  Société Nationale des Mines et de la Géologie ...   
536  Direction Générale du Trésor et de la Comptabi...   
537           Société des Hydrocarbures du Tchad (SHT)   
546                                Commune de Koudalwa   
545                                    Commune de Doba   

                                       Agency type ID number (if applicable)  \
1                                Central goverment            Not applicable   
2                                Central goverment            Not applicable   
3                                Central goverment            Not applicable   
4                                Central goverment            Not applicable   
0                                Central goverment            Not applicable   
..                                             ...                       ...   
543  State-owned enterprises & public corporations            Non applicable   
536                              Central goverment            Non applicable   
537  State-owned enterprises & public corporations            Non applicable   
546                               Local government            Non applicable   
545                               Local government            Non applicable   

    Total reported      Country ISO Code  Year  Start Date    End Date  
1       1367722942  Afghanistan      AFG  2018  2017/12/21  2018/12/20  
2    1478934310.56  Afghanistan      AFG  2018  2017/12/21  2018/12/20  
3            34000  Afghanistan      AFG  2018  2017/12/21  2018/12/20  
4              NaN  Afghanistan      AFG  2018  2017/12/21  2018/12/20  
0       1441453501  Afghanistan      AFG  2018  2017/12/21  2018/12/20  
..             ...          ...      ...   ...         ...         ...  
543            NaN         Chad      TCD  2018  2018/01/01  2018/12/31  
536   316949335.62         Chad      TCD  2018  2018/01/01  2018/12/31  
537   680650556.22         Chad      TCD  2018  2018/01/01  2018/12/31  
546            NaN         Chad      TCD  2018  2018/01/01  2018/12/31  
545            NaN         Chad      TCD  2018  2018/01/01  2018/12/31  

[140 rows x 9 columns]

#### Part 4 - Government revenues

#### Results
- 65 out of 2319 (2.80%) rows are possible red flags

In [10]:
redflags_part_4_2 = get_redflags2(df_part_4, 2)
num_rf_rows(df_part_4, redflags_part_4_2)
display(redflags_part_4_2)

1585 out of 2319 (68.35%) rows are possible red flags


GFS Classification          Sector  \
2                Emission and pollution taxes (114522E)          Mining   
0                Emission and pollution taxes (114522E)       Oil & Gas   
1                Emission and pollution taxes (114522E)          Mining   
8                          Other rent payments (1415E5)          Mining   
13                Fines, penalties, and forfeits (143E)          Mining   
...                                                 ...             ...   
2306            Customs and other import duties (1151E)  Not applicable   
2316    From government participation (equity) (1412E2)           Other   
2315    From government participation (equity) (1412E2)          Mining   
2318  Delivered/paid to state-owned enterprise(s) (1...             Oil   
2317  Delivered/paid to state-owned enterprise(s) (1...             Oil   

                          Revenue stream name  \
2           Environmental License Renewal Fee   
0                        Waste Management Fee   
1                   Environmental License Fee   
8                     Site Accommodation Rent   
13                  Penalties of Late Payment   
...                                       ...   
2306    Droit de Douane à l’Importation (DDI)   
2316               Dividendes versés à l'Etat   
2315               Dividendes versés à l'Etat   
2318  Vente du pétrole collectés par SHT PCCL   
2317       Vente du pétrole collectés par SHT   

                                      Government entity Revenue value  \
2              National Environmental Protection Agency            -    
0              National Environmental Protection Agency            -    
1              National Environmental Protection Agency         47000   
8     Ministry of Mines and Petroleum (Revenue Depar...       2446728   
13    Ministry of Mines and Petroleum (Revenue Depar...          8514   
...                                                 ...           ...   
2306  Direction Générale du Trésor et de la Comptabi...           NaN   
2316  Direction Générale du Trésor et de la Comptabi...       1457152   
2315  Direction Générale du Trésor et de la Comptabi...         27414   
2318           Société des Hydrocarbures du Tchad (SHT)  233804963.54   
2317           Société des Hydrocarbures du Tchad (SHT)  446845592.69   

     Currency      Country ISO Code  Year  Start Date    End Date  
2         AFN  Afghanistan      AFG  2018  2017-12-21  2018-12-20  
0         AFN  Afghanistan      AFG  2018  2017-12-21  2018-12-20  
1         AFN  Afghanistan      AFG  2018  2017-12-21  2018-12-20  
8         AFN  Afghanistan      AFG  2018  2017-12-21  2018-12-20  
13        AFN  Afghanistan      AFG  2018  2017-12-21  2018-12-20  
...       ...          ...      ...   ...         ...         ...  
2306      USD         Chad      TCD  2018  2018-01-01  2018-12-31  
2316      USD         Chad      TCD  2018  2018-01-01  2018-12-31  
2315      USD         Chad      TCD  2018  2018-01-01  2018-12-31  
2318      USD         Chad      TCD  2018  2018-01-01  2018-12-31  
2317      USD         Chad      TCD  2018  2018-01-01  2018-12-31  

[1585 rows x 11 columns]

#### Part 5 - Company data

#### Results
- 1583 out of 31882 (4.97%) rows are possible red flags

In [53]:
redflags_part_5_2 = get_redflags2(df_part_5, 2)
num_rf_rows(df_part_5, redflags_part_5_2)
display(redflags_part_5_2)

1583 out of 31882 (4.97%) rows are possible red flags


Company  \
1      North Coal Enterprise (NCE)   
2      North Coal Enterprise (NCE)   
3      North Coal Enterprise (NCE)   
17     North Coal Enterprise (NCE)   
18     North Coal Enterprise (NCE)   
...                            ...   
31375    ROXGOLD BURKINA FASO SARL   
31374    ROXGOLD BURKINA FASO SARL   
31837         Griffiths Energy DOH   
31838        Griffiths Energy CHAD   
31836            Petrochad Mangara   

                                       Government entity  \
1      Ministry of Mines and Petroleum (Revenue Depar...   
2      Ministry of Mines and Petroleum (Revenue Depar...   
3      Ministry of Mines and Petroleum (Revenue Depar...   
17     Ministry of Mines and Petroleum (Revenue Depar...   
18     Ministry of Mines and Petroleum (Revenue Depar...   
...                                                  ...   
31375  Direction Générale du Trésor et de la Comptabi...   
31374  Direction Générale du Trésor et de la Comptabi...   
31837     Direction Générale Technique de Pétrole (DGTP)   
31838     Direction Générale Technique de Pétrole (DGTP)   
31836     Direction Générale Technique de Pétrole (DGTP)   

                           Revenue stream name Levied on project (Y/N)  \
1                                    Royalties                     Yes   
2                                    Royalties                     Yes   
3                                    Royalties                     Yes   
17                                   Royalties                     Yes   
18                                   Royalties                     Yes   
...                                        ...                     ...   
31375                         Frais de dossier                     Yes   
31374                       Taxe Superficiaire                     Yes   
31837  Frais de présentation du rapport annuel                      No   
31838  Frais de présentation du rapport annuel                      No   
31836  Frais de présentation du rapport annuel                      No   

      Reported by project (Y/N)          Project name Reporting currency  \
1                           Yes            EXP 1/2014                AFN   
2                           Yes            EXP 1/2014                AFN   
3                           Yes            EXP 1/2014                AFN   
17                          Yes            EXP 1/2014                AFN   
18                          Yes            EXP 1/2014                AFN   
...                         ...                   ...                ...   
31375                       Yes  ROXGOLD BURKINA FASO                XOF   
31374                       Yes  ROXGOLD BURKINA FASO                XOF   
31837                        No        Non applicable                USD   
31838                        No        Non applicable                USD   
31836                        No        Non applicable                USD   

      Revenue value Payment made in-kind (Y/N) In-kind volume (if applicable)  \
1         386169944                         No                 Not applicable   
2         336623658                         No                 Not applicable   
3         300000000                         No                 Not applicable   
17        200000000                         No                 Not applicable   
18        100000000                         No                 Not applicable   
...             ...                        ...                            ...   
31375         40000                         No                 Non applicable   
31374      10858296                         No                 Non applicable   
31837         74332                         No                 Non applicable   
31838         74332                         No                 Non applicable   
31836         74332                         No                 Non applicable   

      Unit (if applicable)        Comments       Country ISO Code  Year  \

In [16]:
redflags_part_5_3 = get_redflags2(df_part_5, 1)
num_rf_rows(df_part_5, redflags_part_5_3)
display(redflags_part_5_3)

163 out of 31882 (0.51%) rows are possible red flags


Company  \
19     North Coal Enterprise (NCE)   
3      North Coal Enterprise (NCE)   
18     North Coal Enterprise (NCE)   
166            Khoshak Brothers Co   
100            Khoshak Brothers Co   
...                            ...   
27801             Ithaca Energy UK   
27840               Perenco UK Ltd   
28047                 Centrica PLC   
28381             INEOS Industries   
28472       Severn Sands Group Ltd   

                                       Government entity  \
19     Ministry of Mines and Petroleum (Revenue Depar...   
3      Ministry of Mines and Petroleum (Revenue Depar...   
18     Ministry of Mines and Petroleum (Revenue Depar...   
166    Ministry of Mines and Petroleum (Revenue Depar...   
100    Ministry of Mines and Petroleum (Revenue Depar...   
...                                                  ...   
27801                          Oil & Gas Authority (OGA)   
27840                          Oil & Gas Authority (OGA)   
28047                          Oil & Gas Authority (OGA)   
28381                             The Crown Estate (TCE)   
28472                             The Crown Estate (TCE)   

                    Revenue stream name Levied on project (Y/N)  \
19                            Royalties                     Yes   
3                             Royalties                     Yes   
18                            Royalties                     Yes   
166                           Royalties                     Yes   
100                           Royalties                     Yes   
...                                 ...                     ...   
27801            Petroleum Licence Fees                     Yes   
27840            Petroleum Licence Fees                     Yes   
28047    Oil & Gas Authority (OGA) Levy                     Yes   
28381  Payments to the Crown Estate O&G                     Yes   
28472  Payments to the Crown Estate M&Q                     Yes   

      Reported by project (Y/N)             Project name Reporting currency  \
19                          Yes               EXP 1/2014                AFN   
3                           Yes               EXP 1/2014                AFN   
18                          Yes               EXP 1/2014                AFN   
166                         Yes              EXPL 2/2012                AFN   
100                         Yes              EXPL 2/2012                AFN   
...                         ...                      ...                ...   
27801                       Yes                    P2345                GBP   
27840                       Yes                      P64                GBP   
28047                       Yes                       na                GBP   
28381                       Yes  Pipeline Lease - Breagh                GBP   
28472                       Yes                  PDA/390                GBP   

      Revenue value Payment made in-kind (Y/N) In-kind volume (if applicable)  \
19        100000000                         No                 Not applicable   
3         300000000                         No                 Not applicable   
18        100000000                         No                 Not applicable   
166         7175843                         No                 Not applicable   
100        20405974                         No                 Not applicable   
...             ...                        ...                            ...   
27801         12839             Not applicable                 Not applicable   
27840         17440             Not applicable                 Not applicable   
28047         -2778             Not applicable                 Not applicable   
28381         11800             Not applicable                 Not applicable   
28472         19716             Not applicable                 Not applicable   

      Unit (if applicable)    Comments         Country ISO Code  Year  \
19          Not applicable  2018-11-19     Afghan

#### Part 1 - About

Columns to check:
- Country or area name
- Start Date

***Flagged if rows are similar in at least 2 columns.***

#### Results
- 0 redflag columns

In [44]:
columns_1 = ["Country or area name", "Start Date"]

redflags_part_1 = get_redflags(df_part_1, columns_1, 2)
num_rf_rows(df_part_1, redflags_part_1)
display(redflags_part_1)

0 out of 73 (0.00%) rows are possible red flags


Empty DataFrame
Columns: [Country or area name, ISO Alpha-3 Code, National currency name, National currency ISO-4217, Start Date, End Date, Has an EITI Report been prepared by an Independent Administrator?, What is the name of the company?, Date that the EITI Report was made public, URL, EITI Report, Does the government systematically disclose EITI data at a single location?, Publication date of the EITI data, Website link (URL) to EITI data, Are there other files of relevance?, Date that other file was made public, URL, Does the government have an open data policy?, Open data portal / files, Oil, Gas, Mining (incl. Quarrying), Other, non-upstream sectors, If yes, please specify name (insert new rows if multiple), Number of reporting government entities (incl SOEs if recipient), Number of reporting companies (incl SOEs if payer), Reporting currency (ISO-4217 currency codes), Exchange rate used: 1 USD = , Exchange rate source (URL,…), … by revenue stream, … by government agency, … by company, … by project, Systematically disclosed, Through EITI Reporting, Not applicable, Not available, Name, Organisation, Email address, rowid]
Index: []

[0 rows x 40 columns]

#### Part 3 - Reporting companies' list

Columns to check:
- Full company name
- Company ID number
- Payments to Governments Report

***Flagged if rows are similar in at least 2 columns.***

#### Results
- 1597 out of 3792 (42%) rows are possible red flags
- A lot of the red flags are caused by rows not having a value under the Company ID number and Payments to Governments Report columns
- Most should easily be reconciled by differentiating them using the Country and Year columns

In [11]:
columns_3a = ["Full company name", "Company ID number", "Payments to Governments Report"]
              
redflags_part_3a = get_redflags(df_part_3a, columns_3a, 2)
num_rf_rows(df_part_3a, redflags_part_3a)
display(redflags_part_3a)

1597 out of 3792 (42%) rows are possible red flags


Full company name  \
4                                           Abdul Fatah   
8                                 Afghan Gas Enterprise   
11                             Ahmad Rafi Oraaz Limited   
14                                Amania Mining Company   
17                        Bakhtar Afghan Marble Company   
...                                                 ...   
3765                                   MASHAK PETROLEUM   
3771              Société Nationale de Ciment (SONACIM)   
3775                                                DTP   
3776                                               ETEP   
3787  Société Nationale des Mines et de la Géologie ...   

                                       Company type Company ID number  Sector  \
4                                           Private        9001846329   Other   
8                                           Private     Not available   Other   
11                                          Private        9003746923   Other   
14                                          Private        9000197187   Other   
17                                          Private        1003112081   Other   
...                                             ...               ...     ...   
3765                                        Private     Not available     Oil   
3771  State-owned enterprises & public corporations     Not available  Mining   
3775                                        Private     Not available  Mining   
3776                                        Private     Not available  Mining   
3787  State-owned enterprises & public corporations     Not available  Mining   

     Commodities (comma-seperated) Stock exchange listing or company website  \
4               Construction stone                           Not applicable    
8                      Natural Gas                           Not applicable    
11                            Coal                                       NaN   
14                        Fluoride                           Not applicable    
17                            Talc                           Not applicable    
...                            ...                                       ...   
3765                           Oil                             Not available   
3771                     Quarrying                             Not available   
3775                    Granulates                             Not available   
3776                           BTP                             Not available   
3787                           NaN                             Not available   

     Audited financial statement (or balance sheet, cash flows, profit/loss statement if unavailable)  \
4                                        Not available                                                  
8                                        Not available                                                  
11                                                  NaN                                                 
14                                       Not available                                                  
17                                       Not available                                                  
...                                                 ...                                                 
3765                                      Not available                                                 
3771                                      Not available                                                 
3775                                      Not available                                                 
3776                                      Not available                                                 
3787                                      Not available                                                 

     Payments to Governments Report      Country ISO Code  Year  Start Date  \
4                            139422  Afghanistan      A

In [12]:
redflags_part_3a.sort_values(by=["Country", "Full company name"])

Full company name  \
4                        Abdul Fatah   
222                      Abdul Fatah   
8              Afghan Gas Enterprise   
225            Afghan Gas Enterprise   
11          Ahmad Rafi Oraaz Limited   
...                              ...   
3308  LUMWANA MINING COMPANY LIMITED   
3304       MAAMBA COLLIERIES LIMITED   
3313       MAAMBA COLLIERIES LIMITED   
3302         MOPANI COPPER MINES PLC   
3311         MOPANI COPPER MINES PLC   

                                       Company type Company ID number  \
4                                           Private        9001846329   
222                                         Private        9001846329   
8                                           Private     Not available   
225   State-owned enterprises & public corporations     Not available   
11                                          Private        9003746923   
...                                             ...               ...   
3308                                        Private        1001828755   
3304                                        Private        1001594184   
3313                                        Private        1001594184   
3302                                        Private        1001630233   
3311                                        Private        1001630233   

         Sector Commodities (comma-seperated)  \
4         Other            Construction stone   
222       Other            Construction stone   
8         Other                   Natural Gas   
225   Oil & Gas         Oil, Gas, Condensates   
11        Other                          Coal   
...         ...                           ...   
3308     Mining          Ag, Au, Co, Cu, S, U   
3304     Mining                      COA, PYR   
3313     Mining                      COA, PYR   
3302     Mining                            Cu   
3311     Mining                            Cu   

              Stock exchange listing or company website  \
4                                       Not applicable    
222                                      Not applicable   
8                                       Not applicable    
225                                      Not applicable   
11                                                  NaN   
...                                                 ...   
3308  https://www.barrick.com/English/operations/lum...   
3304                         http://www.maambacoal.com/   
3313                         http://www.maambacoal.com/   
3302                                                NaN   
3311                                                NaN   

     Audited financial statement (or balance sheet, cash flows, profit/loss statement if unavailable)  \
4                                        Not available                                                  
222                                       Not available                                                 
8                                        Not available                                                  
225                            https://momp.gov.af/soes                                                 
11                                                  NaN                                                 
...                                                 ...                                                 
3308                                                NaN                                                 
3304                                                NaN                                                 
3313                                                NaN                                                 
3302                                                NaN                                                 
3311                                                NaN                                                 

     Payments to Governments Report      Country ISO Code  Year  Start Date  \
4                      

In [13]:
table_groupby(redflags_part_3a, 'Year', False)

Year  Number of Rows
1  2018             705
2  2019             396
0  2017             395
3  2020             101

In [14]:
table_groupby(redflags_part_3a, 'Country', False).head(10)

Country  Number of Rows
1               Albania             192
0           Afghanistan             179
18             Mongolia             170
21               Norway             154
27              Ukraine             143
28       United Kingdom             122
26  Trinidad and Tobago              98
9               Germany              68
10                Ghana              68
2               Armenia              52

#### Part 3 - Reporting government entities list

Columns to check:
- Full name of agency
- Agency type
- Total reported

***Flagged if rows are similar in at least 2 columns.***

#### Results
- 373 out of 547 (68%) rows are possible red flags
- A lot of the red flags are caused by rows not having a value under the Total reported column
- Most should easily be reconciled by differentiating them using the Country and Year columns

In [15]:
columns_3b = ["Full name of agency", "Agency type", "Total reported"]

redflags_part_3b = get_redflags(df_part_3b, columns_3b, 2)
num_rf_rows(df_part_3b, redflags_part_3b)
display(redflags_part_3b)

373 out of 547 (68%) rows are possible red flags


Full name of agency  \
0             Ministry of Finance (Revenue Department)   
1             Ministry of Finance (Customs Department)   
2    Ministry of Mines and Petroleum (Revenue Depar...   
3             National Environmental Protection Agency   
4                    Ministry of Industry and Commerce   
..                                                 ...   
460  Electric energy distribution system operator (...   
471  Electric Energy Distribution System Operator (...   
474  Secretaría de Minería (SEMIN), Ministerio de D...   
524                                              CAPAM   
543  Société Nationale des Mines et de la Géologie ...   

                                       Agency type ID number (if applicable)  \
0                                Central goverment            Not applicable   
1                                Central goverment            Not applicable   
2                                Central goverment            Not applicable   
3                                Central goverment            Not applicable   
4                                Central goverment            Not applicable   
..                                             ...                       ...   
460  State-owned enterprises & public corporations                       NaN   
471  State-owned enterprises & public corporations                       NaN   
474                             Central government                       NaN   
524                                          Other                       NaN   
543  State-owned enterprises & public corporations            Non applicable   

    Total reported      Country ISO Code  Year  Start Date    End Date  rowid  
0       1441453501  Afghanistan      AFG  2018  2017-12-21  2018-12-20      0  
1       1367722942  Afghanistan      AFG  2018  2017-12-21  2018-12-21      1  
2    1478934310.56  Afghanistan      AFG  2018  2017-12-21  2018-12-22      2  
3            34000  Afghanistan      AFG  2018  2017-12-21  2018-12-23      3  
4              NaN  Afghanistan      AFG  2018  2017-12-21  2018-12-24      4  
..             ...          ...      ...   ...         ...         ...    ...  
460            NaN      Albania      ALB  2017  2017-01-01  2017-12-31    460  
471            NaN      Albania      ALB  2018  2018-01-01  2018-12-31    471  
474            NaN    Argentina      ARG  2018  2018-01-01  2018-12-31    474  
524            NaN     Cameroon      CMR  2017  2017-01-01  2017-12-31    524  
543            NaN         Chad      TCD  2018  2018-01-01  2018-12-31    543  

[373 rows x 10 columns]

In [16]:
table_groupby(redflags_part_3b, 'Year', False)

Year  Number of Rows
1  2018             128
0  2017             121
2  2019              93
3  2020              31

In [17]:
table_groupby(redflags_part_3b, 'Country', False).head(10)

Country  Number of Rows
12          Ghana              80
4    Burkina Faso              28
16     Madagascar              24
1         Albania              22
34         Zambia              18
20       Mongolia              18
6            Chad              17
32        Ukraine              15
11        Germany              15
7   Cote d'Ivoire              14

#### Part 3 - Reporting projects' list
  
#### Results
- 35 out of 4979 (0.70%) rows are possible red flags

In [48]:
redflags_part_3c_2 = get_redflags2(df_part_3c, 2)
num_rf_rows(df_part_3c, redflags_part_3c_2)
display(redflags_part_3c_2)

35 out of 4979 (0.70%) rows are possible red flags


Full project name  \
22                                          EXPL 3/2012   
102                                         EXPL 3/2012   
482                                  Siana Gold Project   
481                                  Siana Gold Project   
596                                         Non précisé   
595                                         Non précisé   
768   Feasibility study for open pit mining and heap...   
767   Feasibility study for open pit mining and heap...   
832                                                   0   
849                                                   0   
860                                                   0   
891                                                   0   
899                                                   0   
903                                                   0   
909                                                   0   
835                                                   -   
773                                                   0   
831                                                   -   
851                                  Altan tsagaan ovoo   
850                                  Altan tsagaan ovoo   
869                                          Khuren Gol   
868                                          Khuren Gol   
961                   Ambatovy - AMBATOVY MINERALS S.A.   
960                   Ambatovy - AMBATOVY MINERALS S.A.   
963            Rio Tinto - QIT MADAGASCAR MINERALS S.A.   
962            Rio Tinto - QIT MADAGASCAR MINERALS S.A.   
970                    Ambatovy - AMBATOVY MINERALS S.A   
969                    Ambatovy - AMBATOVY MINERALS S.A   
972              Rio Tinto- QIT MADAGASCAR MINERALS S.A   
973              Rio Tinto- QIT MADAGASCAR MINERALS S.A   
971              Rio Tinto- QIT MADAGASCAR MINERALS S.A   
977                                      Not applicable   
4892                                        SOROUBAT-BF   
4893                                        SOROUBAT-BF   
4891                                        SOROUBAT-BF   

     Legal agreement reference number(s): contract, licence, lease, concession, …  \
22                           Mining Exploration License                             
102                          Mining Exploration License                             
482                              MPSA No. 184-2002-XIII                             
481                              MPSA No. 184-2002-XIII                             
596                                         Unspecified                             
595                                         Unspecified                             
768                                          Т/18-12-15                             
767                                          Т/18-12-15                             
832                                                   -                             
849                                                   -                             
860                                                   -                             
891                                                   -                             
899                                                   -                             
903                                                   -                             
909                                                   -                             
835                                                   -                             
773                                                   -                             
831                                                   -                             
851                                          T/19-11-11                             
850                                          T/19-11-11                             
869                                          т/17-03-03                             
868                                        

#### Part 3 - Reporting projects' list

Columns to check:
- Full project name
- Legal agreement reference number(s): contract, licence, lease, concession, …
- Affiliated companies, start with Operator
- Commodities (one commodity/row)

***Flagged if rows are similar in at least 2 columns.***
  
#### Results
- 4707 out of 4979 (95%) rows are possible red flags
- A lot of the red flags are caused by rows not having a value under the Legal agreement reference number(s): contract, licence, lease, concession, … and Commodities (one commodity/row) columns
- Most should easily be reconciled by differentiating them using the Country and Year columns

In [18]:
columns_3c = ["Full project name", "Legal agreement reference number(s): contract, licence, lease, concession, …", "Affiliated companies, start with Operator", "Commodities (one commodity/row)"]

redflags_part_3c = get_redflags(df_part_3c, columns_3c, 2)
num_rf_rows(df_part_3c, redflags_part_3c)
display(redflags_part_3c)

4707 out of 4979 (95%) rows are possible red flags


Full project name  \
0            APL-EP-57   
1            APL-EP-58   
2            APL-EP-59   
3            APL-EP-60   
4            APL-EP-61   
...                ...   
4974        Champs Nya   
4975    Champs Maikeri   
4976     Champs Timbré   
4977    Champs MANGARA   
4978     Champs BADILA   

     Legal agreement reference number(s): contract, licence, lease, concession, …  \
0                                                   NaN                             
1                                                   NaN                             
2                                                   NaN                             
3                                                   NaN                             
4                                                   NaN                             
...                                                 ...                             
4974  Concession d'exploitation NYA du 20/07/2017 (C...                             
4975  Concession d'exploitation Maikeri du 20/07/201...                             
4976  Concession d'exploitation Timbré du 20/07/2017...                             
4977  Autorisation Exclusive d'Exploitation, MANGARA...                             
4978  Autorisation Exclusive d'Exploitation, BADILA ...                             

     Affiliated companies, start with Operator  \
0                       Jabul Siraj Consortium   
1                                Core Drillers   
2                        Amin Karimzai Campany   
3                          Afghan Talc Limited   
4                          Nabi Afghan Company   
...                                        ...   
4974                        Esso, Petronas,SHT   
4975                        Esso, Petronas,SHT   
4976                        Esso, Petronas,SHT   
4977                          PCM/Glencore/SHT   
4978                          PCM/Glencore/SHT   

     Commodities (one commodity/row)      Status Production (volume)     Unit  \
0                                NaN         NaN                 NaN      NaN   
1                                NaN         NaN                 NaN      NaN   
2                                NaN         NaN                 NaN      NaN   
3                                NaN         NaN                 NaN      NaN   
4                                NaN         NaN                 NaN      NaN   
...                              ...         ...                 ...      ...   
4974                Crude oil (2709)  Production              638135  Barrels   
4975                Crude oil (2709)  Production              550314  Barrels   
4976                Crude oil (2709)  Production              598515  Barrels   
4977                Crude oil (2709)  Production             2181729  Barrels   
4978                Crude oil (2709)  Production             1261093  Barrels   

     Production (value) Currency      Country ISO Code  Year  Start Date  \
0                   NaN      NaN  Afghanistan      AFG  2018  2017-12-21   
1                   NaN      NaN  Afghanistan      AFG  2018  2017-12-21   
2                   NaN      NaN  Afghanistan      AFG  2018  2017-12-21   
3                   NaN      NaN  Afghanistan      AFG  2018  2017-12-21   
4                   NaN      NaN  Afghanistan      AFG  2018  2017-12-21   
...                 ...      ...          ...      ...   ...         ...   
4974           34993372      USD         Chad      TCD  2017  2017-01-01   
4975           30177537      USD         Chad      TCD  2017  2017-01-01   
4976           32820733      USD         Chad      TCD  2017  2017-01-01   
4977          119639347      USD         Chad      TCD  2017  2017-01-01   
4978           69154484      USD         Chad      TCD  2017  2017-01-01   

        End Date  rowid  
0     2018-12-20      0  
1     2018-12-20      1  
2     2018-12-20      2  
3     2018-12-20      3  
4     2018-12-20      4  
...          ...    ...  
49

In [19]:
table_groupby(redflags_part_3c, 'Year', False)

Year  Number of Rows
3  2020            1563
2  2019            1465
1  2018            1416
0  2017             263

In [20]:
table_groupby(redflags_part_3c, 'Country', False).head(10)

Country  Number of Rows
28       United Kingdom            1743
27              Ukraine            1703
10                Ghana             168
0           Afghanistan             160
4          Burkina Faso             123
26  Trinidad and Tobago             113
13                 Iraq              81
9               Germany              63
24              Senegal              62
18             Mongolia              62

#### Part 4 - Government revenues

Columns to check:
- Sector
- Revenue stream name
- Government entity
- Revenue value

***Flagged if rows are similar in at least 3 columns.***
  
#### Results
- 1194 out of 2319 (51%) rows are possible red flags
- Most should easily be reconciled by differentiating them using the Country and Year columns

In [21]:
columns_4 = ["Sector", "Government entity", "Revenue value", "Revenue stream name"]

redflags_part_4 = get_redflags(df_part_4, columns_4, 3)
num_rf_rows(df_part_4, redflags_part_4)
display(redflags_part_4)

1194 out of 2319 (51%) rows are possible red flags


GFS Classification     Sector  \
244   Other taxes payable by natural resource compan...        NaN   
254                              Licence fees (114521E)        NaN   
263   Other taxes payable by natural resource compan...        NaN   
265                              Licence fees (114521E)        NaN   
306   Other taxes payable by natural resource compan...  Oil & Gas   
...                                                 ...        ...   
2318  Delivered/paid to state-owned enterprise(s) (1...        Oil   
1882  Other taxes payable by natural resource compan...      Other   
1883  Other taxes payable by natural resource compan...      Other   
471                              Licence fees (114521E)     Mining   
1545              Fines, penalties, and forfeits (143E)     Mining   

                                    Revenue stream name  \
244                              Impuesto de Superficie   
254                            Solicitud de Exploración   
263                              Impuesto de Superficie   
265                            Solicitud de exploración   
306        Drilling &Well Designation Permit (Per Well)   
...                                                 ...   
2318            Vente du pétrole collectés par SHT PCCL   
1882  Other payments to the State and local governme...   
1883  Other payments to the State and local governme...   
471      Tax on sand, gravel and other quarry resources   
1545  Other legal fines and penalties (from other go...   

                                   Government entity Revenue value Currency  \
244   Dirección General de Impuestos Internos (DGII)         28490      DOP   
254               Dirección General de Minería (DGM)           NaN      DOP   
263   Dirección General de Impuestos Internos (DGII)         28490      DOP   
265               Dirección General de Minería (DGM)           NaN      DOP   
306                             Petroleum Commission           NaN      GHS   
...                                              ...           ...      ...   
2318        Société des Hydrocarbures du Tchad (SHT)  233804963.54      USD   
1882                         Municipality of Lushnjë             -      ALL   
1883                    General Directorate of Taxes             -      ALL   
471    Bureau of Local Government and Finance (BLGF)           NaN      PHP   
1545                 Liberia Revenue Authority (LRA)          1000      USD   

                 Country ISO Code  Year  Start Date    End Date  rowid  
244   Dominican Republic      DOM  2019  2019-01-01  2019-12-31    244  
254   Dominican Republic      DOM  2019  2019-01-01  2019-12-31    254  
263   Dominican Republic      DOM  2020  2020-01-01  2020-12-31    263  
265   Dominican Republic      DOM  2020  2020-01-01  2020-12-31    265  
306                Ghana      GHA  2017  2017-01-01  2017-12-31    306  
...                  ...      ...   ...         ...         ...    ...  
2318                Chad      TCD  2018  2018-01-01  2018-12-31   2318  
1882             Albania      ALB  2017  2017-01-01  2017-12-31   1882  
1883             Albania      ALB  2017  2017-01-01  2017-12-31   1883  
471          Philippines      PHL  2018  2018-01-01  2018-12-31    471  
1545             Liberia      LBR  2019    7/1/2018   6/30/2019   1545  

[1194 rows x 12 columns]

In [22]:
table_groupby(redflags_part_4, 'Year', False)

Year  Number of Rows
1  2018             512
0  2017             409
2  2019             195
3  2020              78

In [23]:
table_groupby(redflags_part_4, 'Country', False).head(10)

Country  Number of Rows
12           Madagascar             175
10                Ghana             122
26              Ukraine              90
5                  Chad              88
3          Burkina Faso              85
18              Nigeria              65
1               Albania              59
13                 Mali              56
25  Trinidad and Tobago              55
28               Zambia              51

#### Part 5 - Company data

Columns to check:
- Company
- Project name
- Revenue value
- Revenue stream name

***Flagged if rows are similar in at least 3 columns.***
  
#### Results
- 18129 out of 31882 (57%) rows are possible red flags
- Most should easily be reconciled by differentiating them using the Country and Year columns

In [24]:
columns_5 = ["Company", "Project name", "Revenue value", "Revenue stream name"]

redflags_part_5 = get_redflags(df_part_5, columns_5, 3)
num_rf_rows(df_part_5, redflags_part_5)
display(redflags_part_5)

18129 out of 31882 (57%) rows are possible red flags


Company  \
3      North Coal Enterprise (NCE)   
18     North Coal Enterprise (NCE)   
19     North Coal Enterprise (NCE)   
148                  Core Drillers   
209            Khoshak Brothers Co   
...                            ...   
31619                         APCL   
31647     NOBLE ENERGY CAM LIMITED   
31655                      NEW AGE   
31669              TOWER RESOURCES   
31741                          UHC   

                                       Government entity  \
3      Ministry of Mines and Petroleum (Revenue Depar...   
18     Ministry of Mines and Petroleum (Revenue Depar...   
19     Ministry of Mines and Petroleum (Revenue Depar...   
148             Ministry of Finance (Customs Department)   
209    Ministry of Mines and Petroleum (Revenue Depar...   
...                                                  ...   
31619                Direction Générale des Impôts (DGI)   
31647          Société Nationale des Hydrocarbures (SNH)   
31655                Direction Générale des Impôts (DGI)   
31669          Société Nationale des Hydrocarbures (SNH)   
31741     Direction Générale Technique de Pétrole (DGTP)   

                                     Revenue stream name  \
3                                              Royalties   
18                                             Royalties   
19                                             Royalties   
148                                 Other Fee on Exports   
209                                            Royalties   
...                                                  ...   
31619  Droits Fixes (y compris droits pour attributio...   
31647                                 Bonus de signature   
31655  Droits Fixes (y compris droits pour attributio...   
31669                                 Bonus de signature   
31741            Frais de présentation du rapport annuel   

      Levied on project (Y/N) Reported by project (Y/N)    Project name  \
3                         Yes                       Yes      EXP 1/2014   
18                        Yes                       Yes      EXP 1/2014   
19                        Yes                       Yes      EXP 1/2014   
148                        No                        No             NaN   
209                       Yes                       Yes     EXPL 1/2006   
...                       ...                       ...             ...   
31619                     NaN                       NaN             NaN   
31647                     NaN                       NaN             NaN   
31655                     NaN                       NaN             NaN   
31669                     NaN                       NaN             NaN   
31741                      No                        No  Non applicable   

      Reporting currency Revenue value Payment made in-kind (Y/N)  \
3                    AFN     300000000                         No   
18                   AFN     100000000                         No   
19                   AFN     100000000                         No   
148                  AFN           110                        No    
209                  AFN       5000000                         No   
...                  ...           ...                        ...   
31619                XAF       6000000                        NaN   
31647                XAF     572336000                        NaN   
31655                XAF       6000000                        NaN   
31669                XAF     572336000                        NaN   
31741                USD         75000                         No   

      In-kind volume (if applicable) Unit (if applicable)    Comments  \
3                     Not applicable       Not applicable  2018-11-19   
18                    Not applicable       Not applicable  2018-11-21   
19                    Not applicable       Not applicable  2018-11-19   
148                   Not applicable       Not applicable         NaN   
209                   Not applica

In [25]:
table_groupby(redflags_part_5, 'Year', False)

Year  Number of Rows
1  2018            8258
2  2019            5453
0  2017            2309
3  2020            2109

In [26]:
table_groupby(redflags_part_5, 'Country', False).head(10)

Country  Number of Rows
0      Afghanistan            4122
31         Ukraine            2974
32  United Kingdom            1711
1          Albania            1259
20        Mongolia            1070
28        Tanzania             961
23         Nigeria             950
25     Philippines             894
12           Ghana             688
15         Liberia             557

### Coherence of companies in Part 3 - Reporting companies' list, Part 3 - Reporting government entities list, and Part 3 - Reporting projects list with Part 5 - Company data

In [6]:
def compare_tables(df1, df2, common_columns_df1, common_columns_df2):
    '''
    Compare two tables based on specified columns.

    Parameters:
    - df1 (pandas.DataFrame): The first DataFrame.
    - df2 (pandas.DataFrame): The second DataFrame.
    - common_columns_df1 (list): Columns used in df1 to find common rows.
    - common_columns_df2 (list): Columns used in df2 to find common rows.

    Returns:
    - common_rows (pandas.DataFrame): Rows common to both DataFrames.
    - unique_rows_df1 (pandas.DataFrame): Rows unique to df1.
    - unique_rows_df2 (pandas.DataFrame): Rows unique to df2.

    Example:
    >>> df1 = pd.DataFrame({'Company': ['A', 'B', 'C'], 'Project name': ['P1', 'P2', 'P3'], 'Country': ['X', 'Y', 'Z'], 'Year': [2020, 2021, 2022]})
    >>> df2 = pd.DataFrame({'Full company name': ['A Corp', 'B Corp', 'D Corp'], 'Company type': ['Type1', 'Type2', 'Type3'], 'Company ID number': [101, 102, 103], 'Country': ['X', 'Y', 'Z'], 'Year': [2020, 2021, 2023]})
    >>> common_cols_df1 = ['Country', 'Year']
    >>> common_cols_df2 = ['Country', 'Year']
    >>> common, unique_df1, unique_df2 = compare_tables(df1, df2, common_cols_df1, common_cols_df2)
    >>> print(common)
      Country  Year
    0       X  2020
    1       Y  2021
    >>> print(unique_df1)
      Company Project name
    2       C           P3
    >>> print(unique_df2)
      Full company name Company type  Company ID number
    2            D Corp       Type3                103
    '''

    # Make copies of the input dataframes
    df1_copy = df1.copy()
    df2_copy = df2.copy()

    # Find common rows
    common_rows = pd.merge(df1_copy, df2_copy, left_on=common_columns_df1, right_on=common_columns_df2, how='inner')

    # Find unique rows in df1
    unique_rows_df1 = df1_copy[~df1_copy.set_index(common_columns_df1).index.isin(common_rows.set_index(common_columns_df1).index)]

    # Find unique rows in df2
    unique_rows_df2 = df2_copy[~df2_copy.set_index(common_columns_df2).index.isin(common_rows.set_index(common_columns_df2).index)]

    return {"in table 1 but not in table 2": unique_rows_df1, 
            "in table 2 but not in table 1": unique_rows_df2,
           "in both tables": common_rows}

In [7]:
def compare_tables_drop_duplicates(df1, df2, common_columns_df1, common_columns_df2):
    '''
    Compare two tables based on specified columns and drop duplicates.

    Parameters:
    - df1 (pandas.DataFrame): The first DataFrame.
    - df2 (pandas.DataFrame): The second DataFrame.
    - common_columns_df1 (list): Columns used in df1 to find common rows.
    - common_columns_df2 (list): Columns used in df2 to find common rows.

    Returns:
    - common_rows (pandas.DataFrame): Rows common to both DataFrames with duplicates dropped.
    - unique_rows_df1 (pandas.DataFrame): Rows unique to df1 with duplicates dropped.
    - unique_rows_df2 (pandas.DataFrame): Rows unique to df2 with duplicates dropped.

    Example:
    >>> df1 = pd.DataFrame({'Company': ['A', 'B', 'C'], 'Project name': ['P1', 'P2', 'P3'], 'Country': ['X', 'Y', 'Z'], 'Year': [2020, 2021, 2022]})
    >>> df2 = pd.DataFrame({'Full company name': ['A Corp', 'B Corp', 'D Corp'], 'Company type': ['Type1', 'Type2', 'Type3'], 'Company ID number': [101, 102, 103], 'Country': ['X', 'Y', 'Z'], 'Year': [2020, 2021, 2023]})
    >>> common_cols_df1 = ['Country', 'Year']
    >>> common_cols_df2 = ['Country', 'Year']
    >>> common, unique_df1, unique_df2 = compare_tables_drop_duplicates(df1, df2, common_cols_df1, common_cols_df2)
    >>> print(common)
      Country  Year
    0       X  2020
    1       Y  2021
    >>> print(unique_df1)
      Company Project name
    2       C           P3
    >>> print(unique_df2)
      Full company name Company type  Company ID number
    2            D Corp       Type3                103
    '''

    # Find common rows
    common_rows = pd.merge(df1, df2, left_on=common_columns_df1, right_on=common_columns_df2, how='inner')

    # Drop duplicates in common rows
    common_rows = common_rows.drop_duplicates(subset=common_columns_df1)

    # Drop duplicates in unique rows in df1
    unique_rows_df1 = df1[~df1.set_index(common_columns_df1).index.isin(common_rows.set_index(common_columns_df1).index)]
    unique_rows_df1 = unique_rows_df1.drop_duplicates(subset=common_columns_df1)

    # Drop duplicates in unique rows in df2
    unique_rows_df2 = df2[~df2.set_index(common_columns_df2).index.isin(common_rows.set_index(common_columns_df2).index)]
    unique_rows_df2 = unique_rows_df2.drop_duplicates(subset=common_columns_df2)

    return {"in table 1 but not in table 2": unique_rows_df1, 
            "in table 2 but not in table 1": unique_rows_df2,
            "in both tables": common_rows}


#### Part 3 - Reporting companies' list and Part 5 - Company data

#### RESULTS
- 320 rows are in Part 3 - Reporting companies' list but not in Part 5 - Company data
- 143 rows are in Part 5 - Company data but not in Part 3 - Reporting companies' list

In [10]:
df_part_5_allcaps = df_part_5.copy()
df_part_5_allcaps["Company"] = df_part_5_allcaps["Company"].str.upper()
display(df_part_5_allcaps)
df_part_3a_allcaps = df_part_3a.copy()
df_part_3a_allcaps["Full company name"] = df_part_3a_allcaps["Full company name"].str.upper()
display(df_part_3a_allcaps)

Company  \
0                            NORTH COAL ENTERPRISE (NCE)   
1                            NORTH COAL ENTERPRISE (NCE)   
2                            NORTH COAL ENTERPRISE (NCE)   
3                            NORTH COAL ENTERPRISE (NCE)   
4      HABIB SHAHAB TALC AND MARBLE EXPLOITATION AND ...   
...                                                  ...   
31877  CHINA NATIONAL PETROLEUM CORPORATION INTERNATI...   
31878  CHINA NATIONAL PETROLEUM CORPORATION INTERNATI...   
31879                                  PETROCHAD MANGARA   
31880                                  PETROCHAD MANGARA   
31881                                  PETROCHAD MANGARA   

                                       Government entity  \
0      Ministry of Mines and Petroleum (Revenue Depar...   
1      Ministry of Mines and Petroleum (Revenue Depar...   
2      Ministry of Mines and Petroleum (Revenue Depar...   
3      Ministry of Mines and Petroleum (Revenue Depar...   
4      Ministry of Mines and Petroleum (Revenue Depar...   
...                                                  ...   
31877           Société des Hydrocarbures du Tchad (SHT)   
31878           Société des Hydrocarbures du Tchad (SHT)   
31879           Société des Hydrocarbures du Tchad (SHT)   
31880           Société des Hydrocarbures du Tchad (SHT)   
31881           Société des Hydrocarbures du Tchad (SHT)   

                                Revenue stream name Levied on project (Y/N)  \
0                                         Royalties                     Yes   
1                                         Royalties                     Yes   
2                                         Royalties                     Yes   
3                                         Royalties                     Yes   
4                         Penalties of Late Payment                     NaN   
...                                             ...                     ...   
31877  Redevance sur production collecté par la SHT                      No   
31878                Profit Oil collecté par la SHT                      No   
31879  Redevance sur production collecté par la SHT                      No   
31880                   Tax Oil collecté par la SHT                      No   
31881                Profit Oil collecté par la SHT                      No   

      Reported by project (Y/N)    Project name Reporting currency  \
0                           Yes      EXP 1/2014                AFN   
1                           Yes      EXP 1/2014                AFN   
2                           Yes      EXP 1/2014                AFN   
3                           Yes      EXP 1/2014                AFN   
4                           NaN             NaN                AFN   
...                         ...             ...                ...   
31877                        No  Non applicable                USD   
31878                        No  Non applicable                USD   
31879                        No  Non applicable                USD   
31880                        No  Non applicable                USD   
31881                        No  Non applicable                USD   

      Revenue value Payment made in-kind (Y/N) In-kind volume (if applicable)  \
0         442801100                         No                 Not applicable   
1         386169944                         No                 Not applicable   
2         336623658                         No                 Not applicable   
3         300000000                         No                 Not applicable   
4                18                        NaN                            NaN   
...             ...                        ...                            ...   
31877             -                        Yes                        3543915   
31878             -                        Yes                        2541955   
31879             -                        Yes                         545318   
31880  

Full company name  \
0                                 AMIN KARIMZAI CAMPANY   
1     HABIB SHAHAB TALC AND MARBLE EXPLOITATION AND ...   
2                                   ABAAN RAYAN LIMITED   
3                                 ABAS GHAZNAVI LIMITED   
4                                           ABDUL FATAH   
...                                                 ...   
3787  SOCIÉTÉ NATIONALE DES MINES ET DE LA GÉOLOGIE ...   
3788           TCHAD OIL TRANSPORTATION COMPANY (TOTCO)   
3789        CAMEROUN OIL TRANSPORTATION COMPANY (COTCO)   
3790                       PETROCHAD TRANSPORTATION LTD   
3791            SOCIÉTÉ DE RAFFINAGE DE N’DJAMENA (SRN)   

                                       Company type Company ID number  Sector  \
0                                           Private        1007815085   Other   
1                                           Private        1013655012   Other   
2                                           Private        9004655032   Other   
3                                           Private        9001935742   Other   
4                                           Private        9001846329   Other   
...                                             ...               ...     ...   
3787  State-owned enterprises & public corporations     Not available  Mining   
3788                                        Private         600010746   Other   
3789                                        Private    M089700006137L   Other   
3790                                        Private         600008367   Other   
3791                                        Private         600008474   Other   

     Commodities (comma-seperated)  \
0                             Talc   
1         Talc, Construction stone   
2                             Coal   
3                             Coal   
4               Construction stone   
...                            ...   
3787                           NaN   
3788                 Oil transport   
3789                 Oil transport   
3790                 Oil transport   
3791                      Refinery   

              Stock exchange listing or company website  \
0                                       Not applicable    
1                                       Not applicable    
2                                                   NaN   
3                                                   NaN   
4                                       Not applicable    
...                                                 ...   
3787                                      Not available   
3788                                      Not available   
3789                                      Not available   
3790  https://investir.lesechos.fr/cours/action-glen...   
3791                                      Not available   

     Audited financial statement (or balance sheet, cash flows, profit/loss statement if unavailable)  \
0                                        Not available                                                  
1                                        Not available                                                  
2                                        Not available                                                  
3                                        Not available                                                  
4                                        Not available                                                  
...                                                 ...                                                 
3787                                      Not available                                                 
3788                                      Not available                                                 
3789                                      Not available                                                 
3790                                      Not available                                                 
3791                               

In [11]:
common_columns_3a5 = ["Full company name", "Country", "Year"]
common_columns_53a = ["Company", "Country", "Year"]

# for key, data in compare_tables(df_part_3a, df_part_5, common_columns_3a5, common_columns_53a).items():
#     print(key)
#     display(data)

compare_3a5_allcaps = compare_tables_drop_duplicates(df_part_3a_allcaps, df_part_5_allcaps, common_columns_3a5, common_columns_53a)

print("Duplicate rows removed")
for key, data in compare_3a5_allcaps.items():
    print(f'{key}: {data.shape[0]} rows')

Duplicate rows removed
in table 1 but not in table 2: 317 rows
in table 2 but not in table 1: 140 rows
in both tables: 3469 rows


In [19]:
compare_3a5_allcaps["in table 1 but not in table 2"].to_csv("data/part3a5_allcaps.csv", index=False)

In [12]:
common_columns_3a5 = ["Full company name", "Country", "Year"]
common_columns_53a = ["Company", "Country", "Year"]

# for key, data in compare_tables(df_part_3a, df_part_5, common_columns_3a5, common_columns_53a).items():
#     print(key)
#     display(data)

compare_3a5 = compare_tables_drop_duplicates(df_part_3a, df_part_5, common_columns_3a5, common_columns_53a)

print("Duplicate rows removed")
for key, data in compare_3a5.items():
    print(f'{key}: {data.shape[0]} rows')

Duplicate rows removed
in table 1 but not in table 2: 320 rows
in table 2 but not in table 1: 143 rows
in both tables: 3467 rows


In [41]:
100*320/df_part_3a.drop_duplicates(subset=["Full company name", "Country", "Year"]).shape[0]

8.449960390810668

In [40]:
100*143/df_part_5.drop_duplicates(subset=["Company", "Country", "Year"]).shape[0]

3.961218836565097

#### Part 3 - Reporting government entities' list and Part 5 - Company data

#### RESULTS
- 154 rows are in Part 3 - Reporting government entities' list but not in Part 5 - Company data
- 27 rows are in Part 5 - Company data but not in Part 3 - Reporting government entities' list

In [5]:
common_columns_3b5 = ["Full name of agency", "Country", "Year"]
common_columns_53b = ["Government entity", "Country", "Year"]

# for key, data in compare_tables(df_part_3b, df_part_5, common_columns_3b5, common_columns_53b).items():
#     print(key)
#     display(data)

compare_3b5 = compare_tables_drop_duplicates(df_part_3b, df_part_5, common_columns_3b5, common_columns_53b)

print("Duplicate rows removed")
for key, data in compare_3b5.items():
    print(f'{key}: {data.shape[0]} rows')

Duplicate rows removed
in table 1 but not in table 2: 154 rows
in table 2 but not in table 1: 27 rows
in both tables: 389 rows


In [43]:
100*154/df_part_3b.drop_duplicates(subset=["Full name of agency", "Country", "Year"]).shape[0]

28.360957642725598

In [42]:
100*27/df_part_5.drop_duplicates(subset=["Government entity", "Country", "Year"]).shape[0]

6.490384615384615

#### Part 3 - Reporting projects' list and Part 5 - Company data

#### RESULTS
- 749 rows are in Part 3 - Reporting projects' list but not in Part 5 - Company data
- 556 rows are in Part 5 - Company data but not in Part 3 - Reporting projects' list

In [8]:
common_columns_3c5 = ["Full project name", "Country", "Year"]
common_columns_53c = ["Project name", "Country", "Year"]

# for key, data in compare_tables(df_part_3c, df_part_5, common_columns_3c5, common_columns_53c).items():
#     print(key)
#     display(data)

compare_3c5 = compare_tables_drop_duplicates(df_part_3c, df_part_5, common_columns_3c5, common_columns_53c)

print("Duplicate rows removed")
for key, data in compare_3c5.items():
    print(f'{key}: {data.shape[0]} rows')

Duplicate rows removed
in table 1 but not in table 2: 749 rows
in table 2 but not in table 1: 556 rows
in both tables: 3164 rows


In [45]:
100*749/df_part_3c.drop_duplicates(subset=["Full project name", "Country", "Year"]).shape[0]

19.141323792486585

In [44]:
100*556/df_part_5.drop_duplicates(subset=["Project name", "Country", "Year"]).shape[0]

14.946236559139784

### Compare revenue totals between Part 4 - Government revenues and Part 5 - Company data

#### RESULTS

In [7]:
rev_part_4 = df_part_4.copy()
rev_part_5 = df_part_5.copy()

# Convert "Revenue value" to numeric
rev_part_4["Revenue value"] = pd.to_numeric(rev_part_4["Revenue value"], errors="coerce")
rev_part_5["Revenue value"] = pd.to_numeric(rev_part_5["Revenue value"], errors="coerce")

# Group and sum
# rev_part_4_sum = rev_part_4.groupby(["Country"])["Revenue value"].sum()
# rev_part_5_sum = rev_part_5.groupby(["Country"])["Revenue value"].sum()

rev_part_4_sum = rev_part_4.groupby(["Country", "Year"])["Revenue value"].sum()
rev_part_5_sum = rev_part_5.groupby(["Country", "Year"])["Revenue value"].sum()

# Calculate the difference and format as a percentage
difference = (100 * (rev_part_4_sum - rev_part_5_sum) / rev_part_4_sum).sort_values(ascending=False).reset_index()

# # Rename and style the column
diff_perc = difference.rename(columns={"Revenue value": "Difference in computed revenue (%)<br>[Government revenues - Company data]"}).style.format({'Difference in computed revenue (%)<br>[Government revenues - Company data]': '{:.2f}'})

diff_perc

### SOEs only

In [17]:
df_part_3a_soe = df_part_3a[df_part_3a["Company type"] == "State-owned enterprises & public corporations"]
df_part_3a_soe_non_opt = df_part_3a_non_opt[df_part_3a_non_opt["Company type"] == "State-owned enterprises & public corporations"]
df_part_5_soe = pd.merge(df_part_5, df_part_3a_soe[['Full company name', 'Country', 'Year']], left_on=['Company', 'Country', 'Year'], right_on=['Full company name', 'Country', 'Year'], how='inner').drop(columns=["Full company name"])
df_part_5_soe_non_opt = pd.merge(df_part_5_non_opt, df_part_3a_soe[['Full company name', 'Country', 'Year']], left_on=['Company', 'Country', 'Year'], right_on=['Full company name', 'Country', 'Year'], how='inner').drop(columns=["Full company name"])

In [26]:
redflags_part_3a_soe = get_redflags2(df_part_3a_soe, 2)
num_rf_rows(df_part_3a_soe, redflags_part_3a_soe)
display(redflags_part_3a_soe)

0 out of 168 (0.00%) rows are possible red flags


Empty DataFrame
Columns: [Full company name, Company type, Company ID number, Sector, Commodities (comma-seperated), Stock exchange listing or company website, Audited financial statement (or balance sheet, cash flows, profit/loss statement if unavailable), Payments to Governments Report, Country, ISO Code, Year, Start Date, End Date]
Index: []

In [25]:
redflags_part_5_soe = get_redflags2(df_part_5_soe, 1)
num_rf_rows(df_part_5_soe, redflags_part_5_soe)
display(redflags_part_5_soe)

0 out of 2653 (0.00%) rows are possible red flags


Empty DataFrame
Columns: [Company, Government entity, Revenue stream name, Levied on project (Y/N), Reported by project (Y/N), Project name, Reporting currency, Revenue value, Payment made in-kind (Y/N), In-kind volume (if applicable), Unit (if applicable), Comments, Country, ISO Code, Year, Start Date, End Date]
Index: []

### TESTS

In [33]:
sample = pd.DataFrame({
    "Full name of agency": ["A", "A", "B", "B", "C", "D", "E"],
    "Agency type": ["pri", "pri", "pri", "soe", "soe", "soe", "soe"],
    "Total reported": [0, 0, 1, 1, 2, 2, 5]
})

sample

Full name of agency Agency type  Total reported
0                   A         pri               0
1                   A         pri               0
2                   B         pri               1
3                   B         soe               1
4                   C         soe               2
5                   D         soe               2
6                   E         soe               5

In [34]:
# SAMPLE TEST
sample = pd.DataFrame({
    "Full name of agency": ["A", "A", "B", "B", "C", "D", "E"],
    "Agency type": ["pri", "pri", "pri", "soe", "soe", "soe", "soe"],
    "Total reported": [0, 0, 1, 1, 2, 2, 5]
})

columns = ["Full name of agency", "Agency type", "Total reported"]

get_redflags(sample, columns, 2)

Full name of agency Agency type  Total reported  rowid
0                   A         pri               0      0
1                   A         pri               0      1
2                   B         pri               1      2
3                   B         soe               1      3
4                   C         soe               2      4
5                   D         soe               2      5

In [35]:
# Sample data for sample_companies_list
sample_companies_list_data = {
    "Full company name": ["A Corp", "B Corp", "C Corp", "D Corp", "E Corp", "B Corp", "F Corp"],
    "Company type": ["Type1", "Type2", "Type3", "Type1", "Type2", "Type2", "Type3"],
    "Company ID number": [101, 102, 103, 104, 105, 102, 106],
    "Country": ["X", "Y", "Z", "X", "Y", "Y", "Z"],
    "Year": [2020, 2021, 2022, 2023, 2020, 2021, 2023]
}

sample_company_list = pd.DataFrame(sample_companies_list_data)

# Sample data for sample_company_data
sample_company_data_data = {
    "Company": ["A Corp", "B Corp", "C Corp", "E Corp", "F Corp", "C Corp", "G Corp"],
    "Project name": ["P1", "P2", "P3", "P4", "P5", "P3", "P6"],
    "Country": ["X", "Y", "Z", "X", "Y", "Z", "X"],
    "Year": [2020, 2021, 2022, 2023, 2022, 2023, 2021]
}

sample_company_data = pd.DataFrame(sample_company_data_data)

display(sample_company_list)
display(sample_company_data)

Full company name Company type  Company ID number Country  Year
0            A Corp        Type1                101       X  2020
1            B Corp        Type2                102       Y  2021
2            C Corp        Type3                103       Z  2022
3            D Corp        Type1                104       X  2023
4            E Corp        Type2                105       Y  2020
5            B Corp        Type2                102       Y  2021
6            F Corp        Type3                106       Z  2023

Company Project name Country  Year
0  A Corp           P1       X  2020
1  B Corp           P2       Y  2021
2  C Corp           P3       Z  2022
3  E Corp           P4       X  2023
4  F Corp           P5       Y  2022
5  C Corp           P3       Z  2023
6  G Corp           P6       X  2021

In [36]:
common_columns_df1 = ["Full company name", "Year"]
common_columns_df2 = ["Company", "Year"]

for key, data in compare_tables(sample_company_list, sample_company_data, common_columns_df1, common_columns_df2).items():
    print(key)
    display(data)

in table 1 but not in table 2


Full company name Company type  Company ID number Country  Year
3            D Corp        Type1                104       X  2023
4            E Corp        Type2                105       Y  2020
6            F Corp        Type3                106       Z  2023

in table 2 but not in table 1


Company Project name Country  Year
3  E Corp           P4       X  2023
4  F Corp           P5       Y  2022
5  C Corp           P3       Z  2023
6  G Corp           P6       X  2021

in both tables


Full company name Company type  Company ID number Country_x  Year Company  \
0            A Corp        Type1                101         X  2020  A Corp   
1            B Corp        Type2                102         Y  2021  B Corp   
2            C Corp        Type3                103         Z  2022  C Corp   
3            B Corp        Type2                102         Y  2021  B Corp   

  Project name Country_y  
0           P1         X  
1           P2         Y  
2           P3         Z  
3           P2         Y

In [37]:
for key, data in compare_tables_drop_duplicates(sample_company_list, sample_company_data, common_columns_df1, common_columns_df2).items():
    print(key)
    display(data)

in table 1 but not in table 2


Full company name Company type  Company ID number Country  Year
3            D Corp        Type1                104       X  2023
4            E Corp        Type2                105       Y  2020
6            F Corp        Type3                106       Z  2023

in table 2 but not in table 1


Company Project name Country  Year
3  E Corp           P4       X  2023
4  F Corp           P5       Y  2022
5  C Corp           P3       Z  2023
6  G Corp           P6       X  2021

in both tables


Full company name Company type  Company ID number Country_x  Year Company  \
0            A Corp        Type1                101         X  2020  A Corp   
1            B Corp        Type2                102         Y  2021  B Corp   
2            C Corp        Type3                103         Z  2022  C Corp   

  Project name Country_y  
0           P1         X  
1           P2         Y  
2           P3         Z

In [38]:
# for each row, compare the column combinations for all other rows
# get True or False values for each cell
# get rows with False <= 2

In [39]:
# import pandas as pd

# sample = pd.DataFrame({
#     "Full name of agency": ["A", "A", "B", "B", "C", "D", "E"],
#     "Agency type": ["pri", "pri", "pri", "soe", "soe", "soe", "soe"],
#     "Total reported": [0, 0, 1, 1, 2, 2, 5],
#     "rowid": [0, 1, 2, 3, 4, 5, 6]
# })

# problematic_rows = pd.DataFrame()

# for index, row in df_part_5.iterrows():
#     current_row = row
#     other_rows = df_part_5.drop(index)  # Drop the current row
#     # other_rows = sample  # Drop the current row
#     frows = (other_rows.values == current_row.values)
#     # display(frows)
#     # display(other_rows[(~frows).sum(axis=1) <= 2])
#     # for r in frows:
#     #     print(r)
#     #     print((~r).sum())
#     #     if (~r).sum() <= 2:
#     rows_with_num_false = other_rows[(~frows).sum(axis=1) <= 2]
#     problematic_rows = pd.concat([problematic_rows, rows_with_num_false], ignore_index=False)
            
#     # num_false = (current_row != other_rows).sum(axis=1).sum()  # Count number of False values
#     # print(f"Number of False values in row {index}: {num_false}")


# unique_problematic_rows = problematic_rows.drop_duplicates()

# display(unique_problematic_rows)
# unique_problematic_rows.shape

In [40]:
# how to use results
# for each row
# check if row is already corrected
# if yes, go to next row
# if not, check duplicate with column
# correct duplicate with "row" (solve inconsistency, mark row for deletion), note duplicate with "row" is corrected
# repeat